// Exact bundled-origin/asset simulation; physical Android Intent acceptance is separate.
const{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
const O=process.env.HANDOFF_EVIDENCE_DIR;if(!O)throw Error('Set HANDOFF_EVIDENCE_DIR outside Git');
const R=process.cwd(),S=path.join(R,'src/sugarglider/web/static'),origin='https://appassets.androidplatform.net';
const draft=JSON.parse(fs.readFileSync('examples/itinerary-drafts/versailles-tourist-loop.json','utf8')),raw=JSON.stringify(draft,null,2);
const sizes=[['phone360',360,800],['phone390',390,844],['phone412',412,915],['short',390,420],['text200',390,844]];
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',args:['--no-sandbox','--enable-unsafe-swiftshader']});const rows=[];try{for(const[name,width,height]of sizes){
 const context=await browser.newContext({viewport:{width,height},isMobile:true,hasTouch:true,serviceWorkers:'block'}),page=await context.newPage(),external=[],errors=[];page.on('pageerror',e=>errors.push(e.message));const allowed=new Set(fs.readFileSync('android/shell-assets.txt','utf8').split('\n').filter(n=>n&&!n.startsWith('#')));
 await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin!==origin){external.push(u.href);return route.abort()}if(u.pathname==='/seed')return route.fulfill({contentType:'text/html',body:'<html></html>'});const n=u.pathname==='/'?'index.html':u.pathname==='/v1/ui/config'?'android_ui_config.json':u.pathname.startsWith('/static/')?decodeURIComponent(u.pathname.slice(8)):null;if(!n||!allowed.has(n)||u.search)return route.fulfill({status:404,body:''});const mime={'.js':'application/javascript','.mjs':'application/javascript','.html':'text/html','.css':'text/css','.json':'application/json','.png':'image/png','.pbf':'application/x-protobuf'}[path.extname(n)];return route.fulfill({contentType:mime||'application/octet-stream',body:fs.readFileSync(path.join(S,n))})});
 await page.addInitScript(({raw})=>{Object.defineProperty(navigator,'onLine',{get:()=>false});window.nativeRequests=[];let nonce,counter=0,pending=raw;const port=window.sugargliderNative={onmessage:null,postMessage(payload){const q=JSON.parse(payload);window.nativeRequests.push(q);if(q.type==='hello')nonce=q.request_id.split('-')[1];let reply;if(q.type==='hello')reply={schema_version:1,request_id:q.request_id,type:'hello_result',outing_slug:null,participant_id:null,active:false,state:'stopped',last_published_at:null,pending_sample:false,stop_warning:null};else if(q.type==='itinerary_dialog_state')reply={schema_version:1,request_id:q.request_id,type:'itinerary_dialog_state_result',open:q.open};else if(q.type==='get_local_route_capabilities')reply={schema_version:1,request_id:q.request_id,type:'local_route_capabilities_result',enabled:true,engine:'valhalla-mobile',engine_version:'0.5.1/valhalla-3.6.3',installed_pack_count:0,installed_pack_ids:[],supported_profile_ids:[],pack_capabilities:[]};if(reply)queueMicrotask(()=>{port.onmessage?.({data:JSON.stringify(reply)});if(q.type==='itinerary_dialog_state'&&pending!==null){const text=pending;pending=null;window.sendNativeDraft(text)}})} };
 window.sendNativeDraft=(text,source_kind='shared_text')=>{const event={schema_version:1,request_id:`native-${nonce}-${++counter}`,type:'external_itinerary_draft',text,source_kind};window.lastNativeEvent=event;port.onmessage({data:JSON.stringify(event)})};window.sendNativeBack=()=>port.onmessage({data:JSON.stringify({schema_version:1,request_id:`native-${nonce}-${++counter}`,type:'itinerary_dialog_back'})});},{raw});
 await page.goto(origin+'/seed');await page.evaluate(async()=>{const{openPwaStore,PWA_STORES}=await import('/static/pwa_store.js'),s=await openPwaStore();await s.put(PWA_STORES.trailProfile,'current',{schema_version:1,display_name:'Handoff acceptance',avatar_key:'forest'});s.close()});await context.setOffline(true);await page.goto(origin+'/');await page.evaluate(async()=>window.S=await import('/static/state.js'));await page.waitForFunction(()=>document.querySelector('#itinerary-dialog').open);if(name==='text200')await page.evaluate(()=>document.documentElement.style.fontSize='32px');
 const checks=[],record=text=>{checks.push(text);console.log(name,text)},snap=label=>page.screenshot({path:path.join(O,'screenshots',name+'-'+label+'.png')}),request=()=>page.evaluate(()=>window.S.currentPlanRequest()),close=async()=>{await page.locator('#itinerary-cancel').click();await page.waitForTimeout(30)},review=async()=>{await page.locator('#itinerary-review').click();assert.equal(await page.locator('#itinerary-preview li').count(),4)},importDraft=async()=>{await review();await page.locator('#itinerary-confirm').click();await page.waitForFunction(()=>!document.querySelector('#itinerary-dialog').open);return request()};
 assert.equal(await page.locator('#itinerary-text').inputValue(),raw);assert(await page.locator('#itinerary-review-stage').isHidden());assert(await page.locator('#itinerary-confirm').isHidden());assert.equal(await page.evaluate(()=>window.S.state.points.length),0);assert.equal(await page.evaluate(()=>window.S.state.autoTour.start),null);record('cold normalized native envelope opens input once after controller readiness; no automatic Review/Import');
 await snap('shared-input');const layout=await page.locator('#itinerary-dialog').evaluate(d=>{const r=d.getBoundingClientRect(),f=d.querySelector('.itinerary-actions').getBoundingClientRect(),body=d.querySelector('.itinerary-body');return{x:r.x,y:r.y,width:r.width,height:r.height,footerBottom:f.bottom,bodyHeight:body.clientHeight,textareaScrollable:d.querySelector('textarea').scrollHeight>d.querySelector('textarea').clientHeight,horizontal:document.documentElement.scrollWidth>innerWidth}});assert(!layout.horizontal&&layout.bodyHeight>40&&layout.footerBottom<=height&&layout.x>=0);await page.locator('#itinerary-review').scrollIntoViewIfNeeded();assert(await page.locator('#itinerary-review').isVisible());record('phone/short/200% text: labeled scrollable textarea and Review/Cancel footer reachable without horizontal overflow');
 const cold=await importDraft();record('explicit Review plus Import applies normal canonical route and reasons, no Generate');
 const manual=async()=>{if(await page.locator('[data-shell-view="plan"]').isVisible())await page.locator('[data-shell-view="plan"]').click();await page.locator('#import-itinerary').click();await page.locator('#itinerary-text').fill(raw);return importDraft()};const manually=await manual();assert.deepEqual(cold,manually);const paths=[{path:'manual',request:manually},{path:'shared_text',request:cold}];
 const resultFixture={candidates:[{id:'existing-candidate',route:{geometry:[[2.11,48.79],[2.12,48.8]]}}]};await page.evaluate(result=>{window.S.state.generationResult=result;window.S.state.generationSourceRequest=window.S.currentPlanRequest();window.S.state.selectedSignature='existing-candidate'},resultFixture);
 const before=await page.evaluate(()=>({request:window.S.currentPlanRequest(),result:window.S.state.generationResult,source:window.S.state.generationSourceRequest,signature:window.S.state.selectedSignature,points:window.S.state.points}));const same=async()=>assert.deepEqual(await page.evaluate(()=>({request:window.S.currentPlanRequest(),result:window.S.state.generationResult,source:window.S.state.generationSourceRequest,signature:window.S.state.selectedSignature,points:window.S.state.points})),before);
 const navigationCount=await page.evaluate(()=>performance.getEntriesByType('navigation').length);await page.evaluate(raw=>window.sendNativeDraft(raw),raw);await same();await close();await same();record('warm external input/close preserves full canonical intent, result fixture, selected candidate and point metadata');
 await page.evaluate(raw=>window.sendNativeDraft(raw),raw);await review();await same();await page.evaluate(()=>window.sendNativeBack());await page.waitForFunction(()=>!document.querySelector('#itinerary-dialog').open);await same();assert.equal(await page.evaluate(()=>performance.getEntriesByType('navigation').length),navigationCount);record('Review plus bridge Back cancels without reload or plan/result mutation');
 await page.evaluate(()=>window.sugargliderNative.onmessage({data:JSON.stringify(window.lastNativeEvent)}));assert(!await page.locator('#itinerary-dialog').evaluate(d=>d.open));record('duplicate external event cannot reopen a cancelled draft');
 for(const sourceKind of ['shared_json_file','opened_json_file']){await page.evaluate(({raw,sourceKind})=>window.sendNativeDraft(raw,sourceKind),{raw,sourceKind});const value=await importDraft();assert.deepEqual(value,manually);paths.push({path:sourceKind,request:value})}record('manual/text/shared-file/opened-file currentPlanRequest deeply equal through actual app import callback');
 await page.evaluate(()=>window.sendNativeDraft('https://example.org/shared'));await page.locator('#itinerary-review').click();assert(await page.locator('#itinerary-error').innerText());assert(await page.locator('#itinerary-review-stage').isHidden());await close();record('URL text fails the same strict Review parser without fetching the URL');
 await page.evaluate(raw=>window.sendNativeDraft('```JSON\n'+raw+'\n```'),raw);await review();await snap('fenced-review');await close();record('fenced JSON uses unchanged strict parser and preview');
 assert.equal(external.length,0);assert(!await page.evaluate(()=>window.nativeRequests.some(q=>['local_route','regional_routing_install','save_gpx'].includes(q.type))));assert.deepEqual(errors,[]);record('zero external requests, automatic native routing, install or GPX actions; no page error');
 rows.push({name,width,height,checks,layout,paths,external,errors,nativeTypes:await page.evaluate(()=>window.nativeRequests.map(q=>q.type)),mode:'Chromium exact bundled origin/strict asset allowlist/native-envelope simulation, no physical Android Intent/IME claim',resultsFixture:true});fs.writeFileSync(path.join(O,'runtime','android-origin-acceptance.json'),JSON.stringify(rows,null,2));await context.close();
 }}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
