import { initializeItineraryDialog } from '../../src/sugarglider/web/static/itinerary_dialog.js';
import { initializeNativeItineraryHandoff, parseExternalItineraryEvent } from '../../src/sugarglider/web/static/native_itinerary_handoff.js';
import { createNativeBridgeTransport } from '../../src/sugarglider/web/static/native_bridge_transport.js';
import { state, currentPlanRequest, WAYPOINT_PRODUCT_DEFAULTS } from '../../src/sugarglider/web/static/state.js';
import { clearPointUndo, rememberPointEdit, commitPointEdit, undoPointEdit, redoPointEdit } from '../../src/sugarglider/web/static/route_edit_history.js';
const assert=(ok,m)=>{if(!ok)throw Error(m)},same=(a,b,m)=>assert(JSON.stringify(a)===JSON.stringify(b),m),sleep=()=>new Promise(r=>setTimeout(r,20));
const NONCE='0123456789abcdef0123456789abcdef',ORIGIN='https://appassets.androidplatform.net';
const base={format:'sugarglider_itinerary_draft',version:1,name:'Versailles',activity:'trail_run',topology:'loop',target_distance_km:8,tolerance_km:2,start:{name:'Start',lat:48.798432,lon:2.122484},end:null,stops:[{name:'A',lat:48.790122,lon:2.118049,reason:'Trees'},{name:'B',lat:48.786583,lon:2.105706,reason:'Scenery'}],order:'as_given'};
const raw=JSON.stringify(base),event=(counter,text=raw,source_kind='shared_text')=>({schema_version:1,request_id:`native-${NONCE}-${counter}`,type:'external_itinerary_draft',text,source_kind});
export async function runAndroidItineraryHandoffHarness(){
 const cases=[],initial=structuredClone(state);let root,client;const html=await(await fetch('../../src/sugarglider/web/static/index.html')).text();root=new DOMParser().parseFromString(html,'text/html').querySelector('#itinerary-dialog');const launcher=document.createElement('button');launcher.textContent='Import itinerary';document.body.append(launcher,root);const el=id=>root.querySelector('#itinerary-'+id);let imports=0,prompts=0;
 const dialog=initializeItineraryDialog({root,launcher,maximumStops:()=>30,capability:()=> 'Routing remains explicit',canImport:()=>true,promptSettings:()=>{prompts++;return{}},onImport:(request,draft)=>{imports++;state.planningMode='waypoint_route';state.planningStrategy='waypoint_route';state.routingProfile=draft.activity;state.options={...WAYPOINT_PRODUCT_DEFAULTS,name:draft.name,targetDistanceKm:draft.target_distance_km,toleranceKm:draft.tolerance_km,waypointOrder:request.waypoint_order};state.waypointEndpoints={start:draft.start,end:draft.end,routeTopology:draft.topology};state.points=draft.stops.map((p,i)=>({...p,id:`itinerary-stop-${i+1}`,constraintStrength:'exact',itineraryReason:p.reason}));clearPointUndo();state.generationResult=null;state.generationSourceRequest=null;state.selectedSignature=null}});
 function oldPlan(){Object.assign(state,structuredClone(initial));state.planningMode='waypoint_route';state.planningStrategy='waypoint_route';state.routingProfile='trail_run';state.waypointEndpoints={start:base.start,end:null,routeTopology:'loop'};state.points=[{name:'Old',lat:48.79,lon:2.11,id:'old',constraintStrength:'exact',itineraryReason:'Existing reason'}];state.options={...WAYPOINT_PRODUCT_DEFAULTS};state.generationResult={candidates:[{id:'old-candidate',geometry:[[2.11,48.79],[2.12,48.8]]}]};state.generationSourceRequest=currentPlanRequest();state.selectedSignature='old-candidate';clearPointUndo();rememberPointEdit('Prior edit');state.points[0].name='Prior';commitPointEdit();undoPointEdit();return structuredClone(state)}
 try{
 const before=oldPlan();assert(dialog.openWithText(raw),'external open');assert(root.open&&!el('input-stage').hidden&&el('review-stage').hidden&&el('confirm').hidden,'input stage');assert(el('text').value===raw&&el('source').textContent==='Shared from another app'&&el('prompt-area').hidden&&!root.querySelector('details').open,'prefill/clean prompt');same(state,before,'no mutation on open');assert(imports===0&&prompts===0,'no automatic parser/import/prompt');cases.push('external_prefill_input_only_no_parse_import_or_plan_mutation');
 dialog.cancel();await sleep();same(state,before,'cancel exact');assert(redoPointEdit()&&state.points[0].name==='Prior','redo preserved');assert(undoPointEdit()&&state.points[0].name==='Old','undo preserved');cases.push('close_without_review_preserves_results_candidate_and_history');
 const reviewedBefore=oldPlan();dialog.openWithText(raw,{sourceKind:'opened_json_file'});el('review').click();assert(!el('review-stage').hidden&&el('source').textContent==='Opened JSON document','review');same(state,reviewedBefore,'review no mutation');dialog.cancel();await sleep();same(state,reviewedBefore,'review cancel exact');cases.push('review_cancel_preserves_full_planner_snapshot');
 const canonical=[];
 for(const path of ['manual','shared_text','shared_json_file','opened_json_file']){oldPlan();if(path==='manual'){launcher.click();el('text').value=raw;assert(el('source').hidden,'manual note hidden')}else dialog.openWithText(raw,{sourceKind:path});assert(el('confirm').hidden,'no automatic review');el('review').click();el('confirm').click();await sleep();canonical.push({path,request:currentPlanRequest(),reasons:state.points.map(p=>p.itineraryReason)});assert(!state.generationResult&&!state.selectedSignature,'callback invalidates');}
 for(const item of canonical)same(item.request,canonical[0].request,'manual/native canonical');window.androidHandoffCanonical=canonical;cases.push('manual_shared_text_shared_file_opened_file_canonical_and_reasons_equal');
 dialog.openWithText('```JSON\n'+raw+'\n```');el('review').click();assert(!el('review-stage').hidden,'same fence parser');dialog.cancel();await sleep();cases.push('same_strict_parser_accepts_existing_single_fence');
 for(const text of['prose','https://example.org/share','<script>window.inboundScript=true</script>','{bad','']){const unchanged=oldPlan();dialog.openWithText(text);el('review').click();assert(el('error').textContent&&el('review-stage').hidden,'strict error');assert(!window.inboundScript,'inert text');same(state,unchanged,'invalid no mutation');dialog.cancel();await sleep();}cases.push('prose_url_html_empty_malformed_are_inert_no_network_or_mutation');
 assert(dialog.openWithText('a'.repeat(65536)),'exact bound');dialog.cancel();await sleep();assert(!dialog.openWithText('a'.repeat(65537))&&!dialog.openWithText('é'.repeat(32769))&&!root.open,'overflow');cases.push('web_boundary_defense_64k_utf8');
 dialog.openWithText(raw);el('review').click();dialog.openWithText('second');assert(el('review-stage').hidden&&el('text').value==='second','replace temporary state');dialog.cancel();await sleep();cases.push('second_handoff_resets_old_review_and_prompt_state');
 const messages=[];const port={onmessage:null,postMessage(payload){const q=JSON.parse(payload);messages.push(q);const reply=q.type==='hello'?{schema_version:1,request_id:q.request_id,type:'hello_result',outing_slug:null,participant_id:null,active:false,state:'stopped',last_published_at:null,pending_sample:false,stop_warning:null}:{schema_version:1,request_id:q.request_id,type:'itinerary_dialog_state_result',open:q.open};queueMicrotask(()=>port.onmessage?.({data:JSON.stringify(reply)}))}};
 const lifecycle=new EventTarget(),transport=createNativeBridgeTransport({port,pageNonce:NONCE,lifecycleTarget:lifecycle});client=initializeNativeItineraryHandoff({dialog,transport,origin:ORIGIN});port.onmessage?.({data:JSON.stringify(event(1))});assert(!root.open,'pretrust ignored');await sleep();assert(messages.some(m=>m.type==='itinerary_dialog_state'&&m.open===false),'ready after controller');cases.push('trusted_hello_then_explicit_dialog_readiness');
 const send=value=>port.onmessage({data:JSON.stringify(value)});const unchanged=oldPlan();send(event(1));assert(root.open&&el('text').value===raw,'trusted draft');same(state,unchanged,'native transport no mutation');assert(messages.at(-1).open===true,'modal announced');dialog.cancel();await sleep();send(event(1));assert(!root.open,'duplicate ignored');cases.push('native_one_shot_event_deduplication');
 send(event(2,'malformed'));el('review').click();assert(el('error').textContent,'malformed first');send(event(3,raw,'shared_json_file'));assert(el('text').value===raw&&el('review-stage').hidden,'valid second');cases.push('malformed_first_valid_second_replaces_temporary_input');
 send({schema_version:1,request_id:`native-${NONCE}-4`,type:'itinerary_dialog_back'});await sleep();assert(!root.open&&messages.at(-1).open===false,'Back closes');same(state,unchanged,'Back exact');cases.push('android_back_cancels_modal_and_preserves_plan');
 for(const bad of [{...event(5),extra:true},{...event(5),schema_version:'1'},{...event(5),source_kind:'provider'},{...event(5),text:'é'.repeat(32769)},{...event(5),request_id:`native-${'f'.repeat(32)}-5`}]){send(bad);assert(!root.open,'invalid/stale ignored')};cases.push('exact_envelope_utf8_and_document_nonce_validation');
 assert(parseExternalItineraryEvent(JSON.stringify(event(6)))!==null&&parseExternalItineraryEvent(JSON.stringify({...event(6),uri:'content://fixture'}))===null,'exact fields');cases.push('native_event_never_accepts_uri_sender_or_other_authority');
 lifecycle.dispatchEvent(new Event('pagehide'));send(event(7));assert(!root.open,'old document invalidated');client.close();cases.push('navigation_epoch_pagehide_invalidates_old_document');
 let subscriptions=0;const remote=initializeNativeItineraryHandoff({dialog,origin:'https://sharing.example',transport:{nativeAvailable:true,subscribeUnsolicited(){subscriptions++;throw Error('No remote binding')}}});remote.close();assert(!subscriptions,'no remote page');cases.push('remote_origins_never_subscribe_or_receive_drafts');
 }finally{client?.close();dialog.cancel();root.remove();launcher.remove();Object.assign(state,initial);clearPointUndo()}
 return cases;
}
