// Real UI input with the existing Yvelines pack and routing service. No device installation.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const O=process.env.UI2_EVIDENCE_DIR, B=process.env.UI2_BASE_URL || 'http://127.0.0.1:8812';
if(!O)throw Error('Set UI2_EVIDENCE_DIR outside Git.');
const sizes=[['phone390',390,844],['phone360',360,800],['phone412',412,915],['desktop1280',1280,800],['desktop1440',1440,900]];
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});
try { for(const [name,width,height] of sizes.filter(s=>!process.env.VIEW_FILTER||s[0]===process.env.VIEW_FILTER || (process.env.VIEW_FILTER==='other'&&s[0]!=='phone390'))){
 const context=await browser.newContext({viewport:{width,height},isMobile:width<500,hasTouch:width<500,serviceWorkers:'block',reducedMotion:'reduce'}),page=await context.newPage();page.setDefaultTimeout(20000);
 const checks=[],entries=[],requests={},results={},errors=[];const record=s=>{checks.push(s);console.log(name,s)};
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await context.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
 await page.goto(B+'/setup');await page.evaluate(async()=>{await(await import('/static/map_pack_store.js')).createMapPackStore().installPack(location.origin+'/pack/map/manifest.json');const{openPwaStore,PWA_STORES}=await import('/static/pwa_store.js'),s=await openPwaStore();await s.put(PWA_STORES.trailProfile,'current',{schema_version:1,display_name:'Acceptance',avatar_key:'forest'});s.close()});await page.goto(B+'/');await page.evaluate(async()=>{window.S=await import('/static/state.js');window.M=await import('/static/map.js')});await page.waitForFunction(()=>window.S.state.config&&document.querySelectorAll('#profile option').length===6);await page.waitForTimeout(800);
 async function view(v){const b=page.locator(`[data-shell-view="${v}"]`);if(await b.isVisible())await b.click();await page.waitForTimeout(250)}
 async function expose(s){await page.locator(s).evaluate(el=>{for(let p=el.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true});await page.locator(s).scrollIntoViewIfNeeded()}
 async function action(s){await view('plan');await expose(s);await page.locator(s).click()}
 async function snap(label){await page.waitForTimeout(200);const file=`after/${name}-${label}.png`;await page.screenshot({path:path.join(O,file)});assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),'no overflow '+label);entries.push({label,file})}
 async function request(){return page.evaluate(()=>window.S.currentPlanRequest())}
 async function tap(x,y){if(width<500)await page.touchscreen.tap(x,y);else await page.mouse.click(x,y);await page.waitForTimeout(250)}
 async function mapTap(lon,lat){await view('map');await page.evaluate(p=>window.M.focusCoordinate(p),[lon,lat]);await page.waitForTimeout(400);const r=await page.locator('#map').boundingBox();await tap(r.x+r.width/2,r.y+r.height/2);console.log('tap',lon,lat,await page.evaluate(()=>({mode:window.S.state.planningMode,count:window.S.state.points.length,poi:window.M.placeMapDiagnostics().selectedId})));}
 async function generate(label){const expected=await request();const response=page.waitForResponse(r=>r.url().endsWith('/v2/plans/generate'),{timeout:240000});await action('#generate');const r=await response;assert.equal(r.status(),200,await r.text());assert.deepEqual(r.request().postDataJSON(),expected);requests[label]=expected;results[label]=await r.json();fs.writeFileSync(path.join(O,"runtime",name+"-"+label+".json"),JSON.stringify({request:expected,result:results[label]},null,2));await page.waitForFunction(()=>window.S.state.request.status==='success');await view('routes');assert(await page.locator('.candidate-select').count()>0);await snap(label+'-routes');await expose('#download-gpx');const d=page.waitForEvent('download');await page.locator('#download-gpx').click();await(await d).saveAs(path.join(O,'after',name+'-'+label+'.gpx'));await view('plan');assert.deepEqual(await request(),expected);record(label+' real routing + result selection + GPX, request unchanged')}
 await view('plan');assert.equal(await page.locator('#profile').inputValue(),'trail_run');assert(await page.locator('#generate').isDisabled());assert(!await page.locator('.planning-mode').isVisible());await page.locator('#target-distance').fill('10');await page.locator('#target-distance').press('Tab');await snap('01-initial-plan');await view('map');await snap('02-initial-map');
 await mapTap(2.122484,48.798432);assert.equal(await page.evaluate(()=>window.S.state.planningMode),'auto_tour');assert(await page.locator('#generate').isEnabled());assert(await page.locator('#generate-top').isEnabled());assert.equal(await page.locator('#map-route-summary').innerText(),'10 km loop');await snap('03-start');const startOnly=await request();await page.locator('#undo-point-edit').click();assert(await page.locator('#generate').isDisabled());await mapTap(2.122484,48.798432);assert.deepEqual(await request(),startOnly);record('A: first map tap sets Start, Auto inferred, both Generate actions; Undo Start restores empty');
 if(name==='phone390')await generate('suggest');
 await action('#clear-points');if(name==='phone390'){await view('map');await page.locator('.maplibregl-ctrl-zoom-in').click({clickCount:4});}await mapTap(2.122484,48.798432);
 const nextStart=(await request()).start;
 for(const p of [[2.118049,48.790122],[2.105706,48.786583],[2.120021,48.783068]])await mapTap(...p);
 assert.equal(await page.evaluate(()=>window.S.state.planningMode),'waypoint_route');assert.equal(await page.evaluate(()=>window.S.state.points.length),3);assert.equal(await page.locator('#map-route-summary').innerText(),'Start → 1 → 2 → 3 → Start');assert(await page.locator('#generate').isEnabled());assert(await page.locator('#generate-top').isEnabled());const three=await request();assert.deepEqual(three.start,nextStart);assert.deepEqual(three.distance_objective,startOnly.distance_objective);assert.equal(three.routing_profile,'trail_run');assert.equal(await page.locator('.required-marker[data-point-index]').count(),3);await snap('04-continuous-stops');await view('plan');await snap('05-three-points-plan');record('B/G: continuous Start + 3 stops, markers/order/summary/readiness/options synchronized');
 await view('map');await page.locator('#undo-point-edit').click();assert.equal((await request()).waypoints.length,2);await mapTap(2.120021,48.783068);assert.deepEqual(await request(),three);record('single-level Undo of latest stop preserves exact request on re-add');
 if(name==='phone390')await generate('connect');
 // Inspect real POIs while the route contains several explicit stops.
 for(const [kind,id,lon,lat] of [['ice','node/9739373333',2.1251258,48.8008765],['ordinary','node/700102346',2.1081054,48.7948727]]){
  await view('map');await page.evaluate(p=>window.M.focusCoordinate(p),[lon,lat]);
  if(kind==='ice')await page.locator('.maplibregl-ctrl-zoom-in').click({clickCount:name==='phone390'?4:2});
  await page.waitForFunction(id=>window.M.placeMapDiagnostics().markerIds.includes(id),id);await page.waitForTimeout(300);
  const before=await request(),beforeResult=await page.evaluate(()=>window.S.state.generationResult);
  const p=await page.evaluate(id=>{const d=window.M.placeMapDiagnostics().positions.find(p=>p.id===id).point,r=document.querySelector('.maplibregl-canvas').getBoundingClientRect();return{x:r.x+d[0],y:r.y+d[1]}},id);await tap(p.x,p.y-(kind==='ice'?12:0));await page.waitForSelector('.maplibregl-popup');assert.equal(await page.evaluate(()=>window.M.placeMapDiagnostics().selectedId),id);assert.deepEqual(await request(),before);assert.deepEqual(await page.evaluate(()=>window.S.state.generationResult),beforeResult);if(kind==='ice')assert((await page.locator('.place-detail-popup').innerText()).includes('Lartecono'));await snap('06-'+kind+'-inspection');
  await page.locator('.maplibregl-popup h3').click();assert.deepEqual(await request(),before);await page.locator('.maplibregl-popup-close-button').click();assert.deepEqual(await request(),before);record('E: '+kind+' POI, popup content and dismissal preserve points/request/generated result');
 }
 // Empty map next to the known viewpoint adds a stop; Undo restores request.
 const beforeNear=await request();const canvas=await page.locator('#map').boundingBox();await tap(canvas.x+canvas.width/2+65,canvas.y+canvas.height/2+45);assert.equal((await request()).waypoints.length,4);await page.locator('#undo-point-edit').click();assert.deepEqual(await request(),beforeNear);record('E: empty map near place adds one stop, Undo exact');
 await action('#set-hard-start');await mapTap(2.123604,48.797441);assert.equal((await request()).waypoints.length,3);assert.notDeepEqual((await request()).start,three.start);record('D: explicit Move Start changes Start only, no extra stop');
 await action('[data-point-index="1"] .point-select');await action('[data-action="remove"]');assert.equal((await request()).waypoints.length,2);await action('[data-point-index="1"] .point-select');await action('[data-action="up"]');assert.equal((await request()).waypoints[0].name,'Point 3');await snap('07-corrected-plan');record('move Start / remove stop 2 / reorder preserves selected points');
 if(name==='phone390')await generate('corrected');
 // Removing the last stops returns to suggestion without losing corrected Start.
 const correctedStart=(await request()).start;
 for(let i=0;i<2;i++){await action('[data-point-index="0"] .point-select');await action('[data-action="remove"]')}
 assert.equal(await page.evaluate(()=>window.S.state.planningMode),'auto_tour');assert.deepEqual((await request()).start,correctedStart);assert(await page.locator('#generate').isEnabled());await view('map');await snap('08-back-to-suggestion');record('C: removing last stop returns to Auto, retains Start/distance and readiness');
 // Original Start marker is an edit affordance, not an additional stop.
 if(name==='phone390')await page.locator('.maplibregl-ctrl-zoom-in').click({clickCount:4});
 await page.evaluate(p=>window.M.focusCoordinate([p.lon,p.lat]),correctedStart);await page.waitForTimeout(350);await page.locator('.required-marker[data-point-index="0"]').click();assert.equal(await page.evaluate(()=>window.S.state.selectedEndpointKind),'start');await action('#set-hard-start');await mapTap(2.122484,48.798432);assert.equal(await page.evaluate(()=>window.S.state.points.length),1);assert.notDeepEqual((await request()).start,correctedStart);record('D: tap Start marker → Move is discoverable; no duplicate point');
 if(name==='phone390'){
  await view('plan');await expose('#route-topology');await page.locator('#route-topology').selectOption('point_to_point');assert(await page.locator('#generate').isDisabled());
  await mapTap(2.118049,48.790122);let open=await request();assert.equal(open.kind,'waypoint_route');assert.equal(open.waypoints.length,0);assert(open.end);assert(await page.locator('#generate').isEnabled());
  await mapTap(2.105706,48.786583);await action('[data-point-index="0"] .point-select');await expose('[data-field="constraintStrength"]');await page.locator('[data-field="constraintStrength"]').selectOption('best_effort');const soft=(await request()).waypoints[0];
  await expose('#route-topology');await page.locator('#route-topology').selectOption('loop');assert.equal((await request()).end,null);assert.deepEqual((await request()).waypoints[0],soft);await snap('09-topology-soft-stop');record('F: normal UI open End / extra soft stop / loop preserve distinct exact endpoints and soft strength');
  await action('[data-action="remove"]');assert.equal((await request()).kind,'auto_tour');await page.locator('#undo-point-edit-plan').click();assert.deepEqual((await request()).waypoints[0],soft);await action('[data-point-index="0"] .point-select');await action('[data-action="remove"]');record('Plan Undo restores removed soft stop across inferred-mode transition');
  for(const[label,w,h,scale]of[['short',390,420,1],['text200',360,640,2]]){await page.setViewportSize({width:w,height:h});await page.evaluate(n=>document.documentElement.style.fontSize=16*n+'px',scale);await view('map');await snap('09-'+label+'-map');const card=await page.locator('.map-intent-bar').boundingBox(),map=await page.locator('#map').boundingBox(),attrib=await page.locator('.maplibregl-ctrl-attrib').boundingBox();assert(card.y>=map.y);assert(card.y+card.height<=attrib.y);assert(card.height<map.height/2);await view('plan');await expose('#generate');assert(await page.locator('#generate').isEnabled());await view('plan');await expose('#generate');assert((await page.locator('#map').boundingBox()).height>=110);await snap('10-'+label+'-plan');record(label+': map retained and Generate reachable without overflow')}
 }
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(O,'after-'+name+'.json'),JSON.stringify({name,checks,entries,requests,results,errors},null,2));await context.close();
} } finally {await browser.close()}
})().catch(e=>{console.error(e);process.exit(1)});
