import { parseItineraryDraft, itineraryDraftToCanonical, buildItineraryPrompt, ITINERARY_MAX_BYTES } from '../../src/sugarglider/web/static/itinerary_draft.js';
import { initializeItineraryDialog } from '../../src/sugarglider/web/static/itinerary_dialog.js';
import { state, currentPlanRequest, WAYPOINT_PRODUCT_DEFAULTS } from '../../src/sugarglider/web/static/state.js';
import { rememberPointEdit, commitPointEdit, undoPointEdit, redoPointEdit, clearPointUndo } from '../../src/sugarglider/web/static/route_edit_history.js';
import { replaceResolvedRouteLocation } from '../../src/sugarglider/web/static/route_point_acquisition.js';
import { renderWaypointEditor } from '../../src/sugarglider/web/static/waypoint_editor.js';
import { validateLocalWaypointRouteRequest } from '../../src/sugarglider/web/static/local_waypoint_route.js';
import { PUBLIC_PROFILE_METADATA } from '../../src/sugarglider/web/static/public_profile_metadata.js';
const assert = (ok, message) => { if (!ok) throw Error(message); };
const sorted = x => JSON.stringify(x, (key,value) => value && typeof value==='object' && !Array.isArray(value) ? Object.fromEntries(Object.keys(value).sort().map(k=>[k,value[k]])) : value);
const same=(a,b,message)=>assert(sorted(a)===sorted(b),message);
const base={format:'sugarglider_itinerary_draft',version:1,name:'Versailles',activity:'trail_run',topology:'loop',target_distance_km:15,tolerance_km:2,start:{name:'Start',lat:48.798432,lon:2.122484},end:null,stops:[{name:'A',lat:48.790122,lon:2.118049,reason:'Trees'},{name:'B',lat:48.786583,lon:2.105706,reason:'Scenery'}],order:'as_given'};
export async function runItineraryDraftHarness(){
 const cases=[]; const initial=structuredClone(state);
 function accepted(name,raw){const d=parseItineraryDraft(raw);assert(d.name===base.name,name);cases.push(name)}
 accepted('raw',JSON.stringify(base));accepted('fence',`\n\`\`\`json\n${JSON.stringify(base)}\n\`\`\`\n`);accepted('uppercase_fence',`\`\`\`JSON\n${JSON.stringify(base)}\n\`\`\``);
 function rejected(name,raw,pattern){let e=null;try{parseItineraryDraft(raw)}catch(error){e=error}assert(e&&pattern.test(e.message),name+': useful error');cases.push(name)}
 rejected('invalid_json','{invalid',/Invalid JSON/);rejected('huge_json',' '.repeat(ITINERARY_MAX_BYTES+1),/64 KiB/);rejected('huge_utf8','é'.repeat(ITINERARY_MAX_BYTES),/64 KiB/);rejected('deep_input','{"foo":'+ '['.repeat(3000)+'0'+']'.repeat(3000)+'}',/deeply nested/);
 rejected('prose','Here is your JSON:\n'+JSON.stringify(base)+'\nEnjoy!',/commentary/);rejected('prose_fence','Here is your JSON:\n```json\n'+JSON.stringify(base)+'\n```\nEnjoy!',/commentary/);rejected('double_fence','```json\n```json\n'+JSON.stringify(base)+'\n```\n```',/JSON/);rejected('untagged_fence','```\n'+JSON.stringify(base)+'\n```',/JSON code fence/);rejected('array_root','[]',/object/);
 const mutations={html_name:d=>d.name='<img src=x onerror=alert(1)>',script_reason:d=>d.stops[0].reason='<script>alert(1)</script>',invalid_lat:d=>d.start.lat=91,invalid_lon:d=>d.start.lon=-181,numeric_string:d=>d.start.lat='48.8',nan_string:d=>d.start.lat='NaN',infinity:d=>d.start.lon=Infinity,activity:d=>d.activity='foot',topology:d=>d.topology='circle',missing_start:d=>delete d.start,loop_end:d=>d.end=base.start,open_missing_end:d=>d.topology='point_to_point',identical_end:d=>{d.topology='point_to_point';d.end=d.start},too_many:d=>d.stops=Array.from({length:31},()=>base.stops[0]),unknown:d=>d.extra=true,stop_unknown:d=>d.stops[0].source='model',duplicate_stop:d=>d.stops[1]={...d.stops[0]},endpoint_duplicate:d=>d.stops[0]={...d.start},endpoint_reason:d=>d.start.reason='X',empty_name:d=>d.stops[0].name=' ',long_name:d=>d.name='x'.repeat(121),long_reason:d=>d.stops[0].reason='x'.repeat(401),null_reason:d=>d.stops[0].reason=null,wrong_format:d=>d.format='canonical',wrong_version:d=>d.version='1',wrong_order:d=>d.order='fixed',missing_order:d=>delete d.order,zero_target:d=>d.target_distance_km=0,high_target:d=>d.target_distance_km=201,low_tolerance:d=>d.tolerance_km=.01,high_tolerance:d=>d.tolerance_km=11,loop_zero_stops:d=>d.stops=[],address:d=>d.start='Versailles',control_text:d=>d.stops[0].reason='hello\u0000world'};
 for(const [name,mutate] of Object.entries(mutations)){let d=structuredClone(base);mutate(d);rejected(name,JSON.stringify(d),/./)}
 for(const activity of Object.keys(PUBLIC_PROFILE_METADATA)){const d=parseItineraryDraft(JSON.stringify({...base,activity}));assert(itineraryDraftToCanonical(d).routing_profile===activity,'registry profile');cases.push('profile_'+activity)}
 const fifteen=structuredClone(base);fifteen.stops=Array.from({length:15},(_,i)=>({name:`Stop ${i+1}`,lat:48.7+i/1000,lon:2.1,reason:'A place'}));
 const retained=itineraryDraftToCanonical(parseItineraryDraft(JSON.stringify(fifteen)));let localError;try{validateLocalWaypointRouteRequest(retained)}catch(error){localError=error}assert(localError?.code==='too_many_waypoints'&&localError.details.maximum===14&&retained.waypoints.length===15,'canonical retains local overflow');cases.push('local_14_limit_preserves_15_exact_stops');
 const thirty=structuredClone(fifteen);thirty.stops=Array.from({length:30},(_,i)=>({name:`Stop ${i+1}`,lat:48.7+i/1000,lon:2.1}));assert(parseItineraryDraft(JSON.stringify(thirty)).stops.length===30,'30 accepted');cases.push('canonical_30_stop_boundary');
 let limitError;try{parseItineraryDraft(JSON.stringify(base),{maximumStops:1})}catch(error){limitError=error}assert(limitError?.message.includes('at most 1'),'configured authority limit');cases.push('configured_stop_limit');
 const boundary=structuredClone(base);boundary.start.lat=-90;boundary.start.lon=180;boundary.stops[0].lat=90;boundary.stops[0].lon=-180;boundary.target_distance_km=1;boundary.tolerance_km=.1;assert(parseItineraryDraft(JSON.stringify(boundary)).start.lon===180,'numeric boundaries');cases.push('coordinate_distance_boundaries');
 for(const topology of ['loop','point_to_point'])for(const order of ['as_given','optimize'])for(const reasons of [true,false]){
  const raw=structuredClone(base);raw.topology=topology;raw.order=order;if(topology==='point_to_point')raw.end={name:'End',lat:48.783068,lon:2.120021};if(!reasons)raw.stops.forEach(p=>delete p.reason);
  const d=parseItineraryDraft(JSON.stringify(raw));const c=itineraryDraftToCanonical(d);
  const expected={schema_version:1,kind:'waypoint_route',name:'Versailles',topology,start:d.start,end:d.end,routing_profile:'trail_run',candidate_count:3,seed:0,distance_objective:{target_m:15000,tolerance_m:2000,maximum_m:null,priority:'flexible'},preferences:{nature:'off',path_selection:'shortest',loop_geometry:'off'},waypoints:d.stops.map((p,i)=>({id:`itinerary-stop-${i+1}`,name:p.name,coordinate:{name:p.name,lat:p.lat,lon:p.lon},constraint_strength:'exact',access_search_radius_m:500,maximum_best_effort_distance_m:null,approach_override:null})),waypoint_order:order==='as_given'?'fixed':'optimize'};
  same(c,expected,'manual canonical baseline');Object.assign(state,structuredClone(initial));state.planningMode='waypoint_route';state.planningStrategy='waypoint_route';state.routingProfile=d.activity;state.options={...WAYPOINT_PRODUCT_DEFAULTS,name:d.name,targetDistanceKm:d.target_distance_km,toleranceKm:d.tolerance_km,waypointOrder:expected.waypoint_order};state.waypointEndpoints={start:d.start,end:d.end,routeTopology:d.topology};state.points=d.stops.map((p,i)=>({...p,id:`itinerary-stop-${i+1}`,constraintStrength:'exact',itineraryReason:p.reason}));same(currentPlanRequest(),expected,'manual editor equality');assert(!JSON.stringify(c).includes('reason'),'reason excluded');validateLocalWaypointRouteRequest(c);cases.push(`canonical_${topology}_${order}_reasons_${reasons}`);
 }
 clearPointUndo();state.request.status='idle';const reason=state.points[0].itineraryReason;
 replaceResolvedRouteLocation({index:0},{lat:48.79,lon:2.11});assert(state.points[0].itineraryReason===reason,'move retains');assert(undoPointEdit()&&redoPointEdit(),'move undo redo');cases.push('move_reason_history');
 state.points[0].itineraryReason='First reason';state.points[1].itineraryReason='Second reason';
 rememberPointEdit('Reorder');state.points.reverse();commitPointEdit();assert(state.points[1].itineraryReason==='First reason','reorder retains');undoPointEdit();assert(state.points[0].itineraryReason==='First reason','undo reason');redoPointEdit();assert(state.points[1].itineraryReason==='First reason','redo reason');cases.push('reorder_reason_history');
 rememberPointEdit('Remove');state.points.splice(1,1);commitPointEdit();assert(state.points.length===1,'removed');undoPointEdit();assert(state.points[1].itineraryReason==='First reason','undo removal');redoPointEdit();assert(state.points.length===1,'redo removal');cases.push('remove_reason_history');
 const list=document.createElement('div');document.body.append(list);renderWaypointEditor({list,points:state.points,selectedIndex:0,visitOrders:new Map(),onSelect:()=>{},onChange:()=>{},onMove:()=>{},onRemove:()=>{},onPlace:()=>{}});assert(list.textContent.includes('Suggested because: Second reason'),'detail reason visible');list.remove();cases.push('detail_reason_text');
 const html=await(await fetch('../../src/sugarglider/web/static/index.html')).text();const doc=new DOMParser().parseFromString(html,'text/html');const root=doc.querySelector('#itinerary-dialog');const launch=document.createElement('button');launch.textContent='Import itinerary';document.body.append(launch,root);let imports=0,copies=0,promptReads=0;const before=structuredClone(state);const p=id=>root.querySelector('#itinerary-'+id);
 initializeItineraryDialog({root,launcher:launch,maximumStops:()=>30,capability:()=> 'Routing service',promptSettings:()=>{promptReads++;return {start:base.start}},canImport:()=>true,onImport:(c,d)=>{imports++;same(c,itineraryDraftToCanonical(d),'commit request')},copyText:async text=>{copies++;assert(text==='edited prompt','copy editable text')}});
 launch.click();assert(root.open&&document.activeElement===p('text'),'native dialog focus');assert(promptReads===0&&copies===0,'no implicit prompt/copy');p('text').value=JSON.stringify(base);p('review').click();assert(!p('review-stage').hidden&&p('preview').querySelectorAll('ol li').length===2,'semantic preview');same(state,before,'preview no mutation');p('back').click();assert(p('text').value===JSON.stringify(base),'Back preserves text');p('review').click();p('cancel').click();await new Promise(r=>setTimeout(r,30));same(state,before,'cancel exact state');assert(imports===0&&!root.open&&document.activeElement===launch,'cancel focus restored');cases.push('preview_back_cancel_exact_and_focus');
 launch.click();p('text').value='{bad';p('review').click();assert(p('error').role==='alert'&&p('error').textContent.includes('Invalid JSON'),'announced error');assert(p('review-stage').hidden,'no invalid preview');cases.push('dialog_validation_alert');
 p('text').value=JSON.stringify(base);p('review').click();p('confirm').click();assert(imports===1&&!root.open,'explicit import only');cases.push('dialog_explicit_commit');
 launch.click();const dt=new DataTransfer();dt.items.add(new File([JSON.stringify(base)],'draft.json',{type:'application/json'}));p('file').files=dt.files;p('file').dispatchEvent(new Event('change'));await new Promise(r=>setTimeout(r,30));assert(p('text').value===JSON.stringify(base),'file paste');assert(imports===1,'file no autoimport');cases.push('file_input_without_auto_commit');
 const huge=new DataTransfer();huge.items.add(new File([' '.repeat(ITINERARY_MAX_BYTES+1)],'huge.json'));p('file').files=huge.files;p('file').dispatchEvent(new Event('change'));await new Promise(r=>setTimeout(r,30));assert(p('error').textContent.includes('64 KiB'),'file bounded before read');cases.push('oversize_file_rejected');
 const fileText=File.prototype.text;let completeFile;File.prototype.text=()=>new Promise(resolve=>{completeFile=resolve});p('file').files=dt.files;p('file').dispatchEvent(new Event('change'));p('cancel').click();launch.click();completeFile(JSON.stringify(base));await new Promise(r=>setTimeout(r,30));assert(p('text').value==='','closed read cannot affect reopened dialog');File.prototype.text=fileText;cases.push('cancelled_file_read_cannot_mutate_reopened_dialog');
 // Disable fetch during all pure operations and prompt dialog actions; no remote work is possible.
 const originalFetch=window.fetch;let calls=0;window.fetch=()=>{calls++;throw Error('network disabled')};
 const prompt=buildItineraryPrompt({start:base.start,activity:'trail_run',topology:'loop'});assert(prompt.includes('48.798432')&&prompt.includes('Only include places whose coordinates'),'resolved explicit prompt');parseItineraryDraft(JSON.stringify(base));itineraryDraftToCanonical(parseItineraryDraft(JSON.stringify(base)));assert(buildItineraryPrompt().includes('Start is missing'),'missing Start truthful');p('create-prompt').click();assert(promptReads===1&&copies===0&&!p('prompt-area').hidden,'explicit visible prompt');p('prompt').value='edited prompt';p('copy-prompt').click();await Promise.resolve();assert(copies===1&&calls===0,'explicit copy zero network');window.fetch=originalFetch;cases.push('offline_parser_converter_prompt_and_explicit_copy');
 p('cancel').click();root.remove();launch.remove();Object.assign(state,initial);clearPointUndo();return cases;
}
