// Real regional-map and routing acceptance. Evidence must stay outside Git.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const O=process.env.ITINERARY_EVIDENCE_DIR,B=process.env.ITINERARY_BASE_URL||'http://127.0.0.1:8840',BEFORE=process.env.ITINERARY_BASELINE_URL||'http://127.0.0.1:8841';
if(!O)throw Error('Set ITINERARY_EVIDENCE_DIR outside Git.');
const sizes=[['phone390',390,844],['phone360',360,800],['phone412',412,915],['short',390,420],['text200',390,844],['desktop1280',1280,800],['desktop1440',1440,900]];
const draft=JSON.parse(fs.readFileSync('examples/itinerary-drafts/versailles-tourist-loop.json'));draft.order='as_given';
const signature=r=>r.candidates.map(c=>({id:c.id,rank:c.rank,roles:c.roles,order:c.actual_waypoint_order,geometry:c.route.geometry,traversal:c.traversal}));
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});const results=[];
try{for(const[name,width,height]of sizes.filter(v=>!process.env.VIEW_FILTER||v[0]===process.env.VIEW_FILTER||process.env.VIEW_FILTER==='other'&&v[0]!=='phone390')){
 const c=await browser.newContext({viewport:{width,height},isMobile:width<500,hasTouch:width<500,serviceWorkers:'block',reducedMotion:'reduce'}),p=await c.newPage();p.setDefaultTimeout(30000);const checks=[],errors=[],external=[];let routeCalls=0;const record=s=>{checks.push(s);console.log(name,s)};
 p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/\/v2\/plans\/(generate|reverse)$/.test(r.url()))routeCalls++});
 await c.route('**/*',r=>{if(new URL(r.request().url()).hostname!=='127.0.0.1'){external.push(r.request().url());return r.abort()}return r.continue()});
 await p.addInitScript(()=>{window.clipboardCopies=[];Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{window.clipboardCopies.push(text)}}});Object.defineProperty(navigator,'onLine',{get:()=>false})});
 await p.goto(B+'/setup');await p.evaluate(async()=>{await(await import('/static/map_pack_store.js')).createMapPackStore().installPack(location.origin+'/pack/map/manifest.json');const{openPwaStore,PWA_STORES}=await import('/static/pwa_store.js'),s=await openPwaStore();await s.put(PWA_STORES.trailProfile,'current',{schema_version:1,display_name:'Acceptance',avatar_key:'forest'});s.close()});
 await p.goto(B+'/');await p.evaluate(async()=>{window.S=await import('/static/state.js');window.M=await import('/static/map.js');window.I=await import('/static/itinerary_draft.js')});await p.waitForFunction(()=>window.S.state.config&&document.querySelectorAll('#profile option').length===6);
 if(name==='text200')await p.evaluate(()=>document.documentElement.style.fontSize='32px');
 async function view(v){const tab=p.locator(`[data-shell-view="${v}"]`);if(await tab.isVisible())await tab.click();await p.waitForTimeout(120)}
 async function expose(selector){await p.locator(selector).evaluate(el=>{for(let a=el.parentElement;a;a=a.parentElement)if(a.tagName==='DETAILS')a.open=true});await p.locator(selector).scrollIntoViewIfNeeded()}
 const req=()=>p.evaluate(()=>window.S.currentPlanRequest());
 const snap=label=>p.screenshot({path:path.join(O,'screenshots',name+'-'+label+'.png')});
 const importCanonical=async(value,filename='plan.json')=>{await p.locator('#request-file').setInputFiles({name:filename,mimeType:'application/json',buffer:Buffer.from(JSON.stringify(value))});await p.waitForFunction(n=>window.S.state.options.name===n,value.name);await p.waitForTimeout(180)};
 const canonical=await p.evaluate(d=>window.I.itineraryDraftToCanonical(window.I.parseItineraryDraft(JSON.stringify(d))),draft);
 await importCanonical(canonical);const original=await req();assert.deepEqual(original,canonical);
 async function generate(label){await view('plan');const expected=await req(),pending=p.waitForResponse(r=>r.url().endsWith('/v2/plans/generate'),{timeout:240000});await p.locator('#generate').click();const response=await pending;assert.equal(response.status(),200,await response.text());assert.deepEqual(response.request().postDataJSON(),expected);const result=await response.json();await p.waitForFunction(()=>window.S.state.request.status==='success');const responseBefore=await c.request.post(BEFORE+'/v2/plans/generate',{data:expected,timeout:240000});assert.equal(responseBefore.status(),200,await responseBefore.text());const baseline=await responseBefore.json();assert.deepEqual(signature(result),signature(baseline));assert(result.candidates.length>0);
  const selected=await p.evaluate(()=>window.S.state.selectedSignature),candidate=result.candidates.find(c=>c.id===selected);
  await view('routes');await expose('#download-gpx');const pendingFile=p.waitForEvent('download');await p.locator('#download-gpx').click();const download=await pendingFile;const file=path.join(O,'runtime',label+'.gpx');await download.saveAs(file);const text=fs.readFileSync(file,'utf8');
  const q=await c.newPage();await q.goto(BEFORE+'/setup');const baselineGpx=await q.evaluate(async candidate=>{const e=(await import('/static/local_gpx_client.js')).createLocalGpxExporter();try{return await(await e.exportCandidate(candidate)).blob.text()}finally{e.close?.()}},baseline.candidates.find(c=>c.id===selected));await q.close();assert.equal(text,baselineGpx);assert(!/itineraryReason|<extensions|<rte[ >]/.test(text));assert.equal((text.match(/<trk>/g)||[]).length,1);assert.equal((text.match(/<trkseg>/g)||[]).length,1);
  fs.writeFileSync(path.join(O,'runtime',label+'.json'),JSON.stringify({request:expected,result,baseline,selected,candidateCount:result.candidates.length,gpxEqual:true},null,2));record(label+': explicit real generation; canonical request, candidates, IDs, order, geometry and GPX equal main');return result;
 }
 if(name==='phone390')await generate('existing-plan');
 await view('plan');const before=await p.evaluate(()=>({request:window.S.currentPlanRequest(),result:window.S.state.generationResult,source:window.S.state.generationSourceRequest,signature:window.S.state.selectedSignature}));const callsBefore=routeCalls;
 await p.locator('#import-itinerary').click();assert(await p.locator('#itinerary-dialog').evaluate(d=>d.open));assert.equal(await p.locator('#itinerary-dialog').getAttribute('aria-labelledby'),'itinerary-title');assert.equal(await p.evaluate(()=>document.activeElement.id),'itinerary-text');await p.locator('#itinerary-text').fill('```JSON\n'+JSON.stringify(draft,null,2)+'\n```');await snap('input');
 assert(await p.locator('#itinerary-text').evaluate(el=>el.labels.length===1&&Boolean(el.getAttribute('aria-describedby'))));record('native modal title, labeled usable textarea, explicit review');
 await p.locator('#itinerary-review').click();assert.equal(await p.locator('#itinerary-preview li').count(),4);assert(await p.locator('#itinerary-preview').innerText().then(t=>t.includes('Start')&&t.includes('Suggested because:')));await snap('preview');
 const layout=await p.locator('#itinerary-dialog').evaluate(d=>{const r=d.getBoundingClientRect(),footer=d.querySelector('.itinerary-actions').getBoundingClientRect(),body=d.querySelector('.itinerary-body');return{rect:{x:r.x,y:r.y,width:r.width,height:r.height},footerBottom:footer.bottom,scrollable:body.scrollHeight>body.clientHeight,pageOverflow:document.documentElement.scrollWidth>innerWidth,bodyClient:body.clientHeight}});assert(!layout.pageOverflow);assert(layout.rect.x>=0&&layout.rect.width<=width);assert(layout.footerBottom<=height);assert(layout.bodyClient>40);record('preview ordered list, reasons, responsive scroll, footer inside viewport, no horizontal overflow');
 // Native modal Tab/Shift+Tab never escape; keyboard can activate Back, Review and Cancel.
 for(let i=0;i<12;i++){await p.keyboard.press('Tab');assert(await p.evaluate(()=>document.querySelector('#itinerary-dialog').contains(document.activeElement)||document.activeElement===document.body))}await p.locator('#itinerary-back').focus();await p.keyboard.press('Enter');assert(await p.locator('#itinerary-review-stage').isHidden());await p.locator('#itinerary-review').focus();await p.keyboard.press('Enter');await p.locator('#itinerary-cancel').focus();await p.keyboard.press('Enter');await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>document.activeElement.id),'import-itinerary');assert.deepEqual(await p.evaluate(()=>({request:window.S.currentPlanRequest(),result:window.S.state.generationResult,source:window.S.state.generationSourceRequest,signature:window.S.state.selectedSignature})),before);assert.equal(routeCalls,callsBefore);record('keyboard trap, Back/review/Cancel; focus restoration and exact existing request/results preserved');
 await p.locator('#import-itinerary').click();await p.locator('#itinerary-file').setInputFiles({name:'itinerary.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(draft))});await p.waitForFunction(()=>document.querySelector('#itinerary-text').value.includes('Versailles gardens'));await p.locator('#itinerary-review').click();await p.locator('#itinerary-confirm').focus();await p.keyboard.press('Enter');assert.deepEqual(await req(),canonical);assert.equal(routeCalls,callsBefore);assert(await p.evaluate(()=>!window.S.state.generationResult&&!window.S.state.generationSourceRequest&&window.S.state.endpointSetMode===null&&window.S.state.movingPointIndex===null));assert(await p.locator('#undo-point-edit').isDisabled());assert(await p.locator('#redo-point-edit').isDisabled());assert.equal(await p.evaluate(()=>window.S.state.selectedPointIndex),0);await expose('#planning-points');assert((await p.locator('.itinerary-reason').innerText()).includes(draft.stops[0].reason));await snap('imported-plan');record('file review and keyboard confirmation; canonical exact points, reasons, result invalidation, placement clear, history boundary, no automatic routing');
 await view('map');await p.waitForTimeout(700);const bounds=await p.evaluate(()=>window.M.currentViewportBounds());assert([draft.start,...draft.stops].every(point=>point.lon>=bounds.west&&point.lon<=bounds.east&&point.lat>=bounds.south&&point.lat<=bounds.north));assert(!await p.locator('#route-dock').innerText().then(t=>t.includes('Suggested because:')));await snap('imported-map');record('map fits Start/all stops, ribbon contains no reason text');
 if(name==='phone390'){
  await view('plan');await expose('#planning-points');await p.locator('.poi-row.selected [data-action="down"]').click();assert.equal(await p.evaluate(()=>window.S.state.points[1].itineraryReason),draft.stops[0].reason);const reordered=await req();record('real detailed-editor reorder preserves reason');
  await p.locator('.poi-row.selected details').evaluate(d=>d.open=true);const lat=p.locator('.poi-row.selected [data-field="lat"]');await lat.fill('48.80315');await lat.press('Tab');const moved=await req();assert.equal(moved.waypoints[1].coordinate.lat,48.80315);assert.equal(await p.evaluate(()=>window.S.state.points[1].itineraryReason),draft.stops[0].reason);record('resolved coordinate editor Move retains reason');
  await p.locator('.poi-row.selected [data-action="remove"]').click();assert.equal((await req()).waypoints.length,3);assert(!(await p.evaluate(()=>window.S.state.points)).some(point=>point.itineraryReason===draft.stops[0].reason));await view('map');await p.locator('#undo-point-edit').click();assert.deepEqual(await req(),moved);assert.equal(await p.evaluate(()=>window.S.state.points[1].itineraryReason),draft.stops[0].reason);await p.locator('#redo-point-edit').click();assert.equal((await req()).waypoints.length,3);await p.locator('#undo-point-edit').click();await p.locator('#undo-point-edit').click();assert.deepEqual(await req(),reordered);record('remove/Undo/Redo restore exact point and reason, Move Undo restores original coordinate');
  await generate('imported-loop-fixed');
  await view('tools');await expose('#export-plan');const pending=p.waitForEvent('download');await p.locator('#export-plan').click();const download=await pending;const output=path.join(O,'runtime','canonical-export.json');await download.saveAs(output);const exported=JSON.parse(fs.readFileSync(output));assert.deepEqual(exported,await req());assert(!JSON.stringify(exported).includes('reason'));record('actual canonical file export contains no itinerary metadata');
  for(const topology of ['loop','point_to_point'])for(const order of ['as_given','optimize']){const d=structuredClone(draft);d.topology=topology;d.order=order;if(topology==='point_to_point')d.end={name:'End near Versailles',lat:48.798432,lon:2.122484};const canonicalCase=await p.evaluate(d=>window.I.itineraryDraftToCanonical(window.I.parseItineraryDraft(JSON.stringify(d))),d);await view('plan');await p.locator('#import-itinerary').click();await p.locator('#itinerary-text').fill(JSON.stringify(d));await p.locator('#itinerary-review').click();if(topology==='point_to_point')assert((await p.locator('#itinerary-preview').innerText()).includes('End'));await p.locator('#itinerary-confirm').click();assert.deepEqual(await req(),canonicalCase);await generate('draft-'+topology+'-'+order)}
  // Compare historical canonical examples against the actual pre-change importer.
  const q=await c.newPage();await q.goto(BEFORE+'/');await q.evaluate(async()=>{window.S=await import('/static/state.js')});await q.waitForFunction(()=>window.S.state.config&&document.querySelectorAll('#profile option').length===6);
  const regressions=[];for(const filename of ['all-pois-generation-request.json','auto-tour-request.json','bastille-22-places-auto-tour.json','bastille-to-marly-auto-tour.json']){const value=JSON.parse(fs.readFileSync('examples/marly/'+filename)),input={name:filename,mimeType:'application/json',buffer:Buffer.from(JSON.stringify(value))};await importCanonical(value,filename);await q.locator('#request-file').setInputFiles(input);await q.waitForFunction(n=>window.S.state.options.name===n,value.name);const after=await req(),prior=await q.evaluate(()=>window.S.currentPlanRequest());assert.deepEqual(after,prior);regressions.push({filename,requestEqual:true});record('canonical example matches pre-change importer: '+filename)}await q.close();fs.writeFileSync(path.join(O,'runtime','canonical-regression.json'),JSON.stringify(regressions,null,2));
  await view('plan');await p.locator('#import-itinerary').click();await p.locator('#itinerary-text').fill('{bad');await p.locator('#itinerary-review').click();assert((await p.locator('#itinerary-error').innerText()).includes('Invalid JSON'));assert.equal(await p.locator('#itinerary-error').getAttribute('role'),'alert');record('actual dialog error is announced without changing current plan');
await p.locator('.itinerary-prompt-helper').evaluate(d=>d.open=true);
  const sampleCount=await p.evaluate(()=>window.clipboardCopies.length);const priorStart=await p.evaluate(()=>window.S.state.autoTour.start);await p.waitForTimeout(1000);let requests=[];const count=request=>requests.push(request.url());await c.setOffline(true);await p.waitForTimeout(1000);p.on('request',count);await p.locator('#itinerary-create-prompt').click();assert.equal(await p.evaluate(()=>window.clipboardCopies.length),sampleCount);assert((await p.locator('#itinerary-prompt').inputValue()).includes(String(priorStart.lat)));await snap('local-prompt');await p.locator('#itinerary-prompt').fill('Reviewed editable prompt');await p.locator('#itinerary-copy-prompt').click();assert.equal(await p.evaluate(()=>window.clipboardCopies.at(-1)),'Reviewed editable prompt');assert.deepEqual(requests,[]);p.off('request',count);await p.locator('#itinerary-cancel').click();await c.setOffline(false);record('network-disabled dialog prompt; no requests, no automatic copy, explicit copy uses edited text');
 }
 assert.equal(errors.length,0,errors.join('\n'));assert.equal(external.length,0,external.join('\n'));results.push({name,width,height,checks,layout,routeCalls,errors,external});fs.writeFileSync(path.join(O,'runtime','acceptance-results'+(process.env.VIEW_FILTER?'-'+process.env.VIEW_FILTER:'')+'.json'),JSON.stringify(results,null,2));await c.close();
}}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
