import { createLocationSearch, validateLocationQuery, normalizeOnlineLocations } from '../../src/sugarglider/web/static/location_search.js';
import { initializeLocationSearchDialog } from '../../src/sugarglider/web/static/location_search_dialog.js';
import { createLocalRegionData } from '../../src/sugarglider/web/static/local_region_data.js';
import { createRegionVersionStore } from '../../src/sugarglider/web/static/region_versions.js';
import { createVersionedRegionComponents } from '../../src/sugarglider/web/static/region_components.js';
import { createLocalRegionClient } from '../../src/sugarglider/web/static/local_region_client.js';
import { distribution } from './pr42_region_components_harness.js';
import { createLocalPlaceNameSearch } from '../../src/sugarglider/web/static/local_places.js';
import { state, saveActivePoints, assignRouteEndpoint, currentPlanRequest, invalidateCandidates } from '../../src/sugarglider/web/static/state.js';
import { addResolvedRouteLocation, replaceResolvedRouteLocation } from '../../src/sugarglider/web/static/route_point_acquisition.js';
import { changeMapTopology, reconcileAutomaticIntent } from '../../src/sugarglider/web/static/automatic_intent.js';
import { clearPointUndo, undoPointEdit, redoPointEdit } from '../../src/sugarglider/web/static/route_edit_history.js';
const assert=(ok,m)=>{if(!ok)throw Error(m)}, same=(a,b,m)=>assert(JSON.stringify(a)===JSON.stringify(b),m);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(f){for(let i=0;i<300;i++){if(f())return;await sleep(10)}throw Error('Timed out')}
async function rejects(f){try{await f()}catch{return}throw Error('Expected rejection')}
const A={name:'Grand Trianon',lat:48.81475,lon:2.10436}, B={name:'Place d’Armes',lat:48.803725,lon:2.124426}, C={name:'Water',lat:48.804,lon:2.124};
const config=()=>({available:true,provider:'ign_geoplateforme',endpoint:'https://geocoder.test/search',attribution:'IGN · BAN / BD TOPO',attribution_url:'https://geocoder.test/terms',coverage:'France'});
const doc=(place=A)=>({type:'FeatureCollection',features:[{type:'Feature',geometry:{type:'Point',coordinates:[place.lon,place.lat]},properties:{name:place.name,city:'Versailles',postcode:'78000',id:'secret-id',extrafields:{ignored:'provider blob'}}}]});
const response=d=>new Response(JSON.stringify(d),{headers:{'Content-Type':'application/json'}});
const noLocal=async()=>({available:false,results:[]});
export async function runLocationSearchHarness(){window.searchCanonicalEvidence=[];const cases=[], initial=structuredClone(state);let root;
try{
 for(const value of['ab','a'.repeat(201),'abc\n','abc\u007f'])await rejects(()=>validateLocationQuery(value));
 assert(validateLocationQuery('  Grand Trianon  ')==='Grand Trianon','trim');cases.push('query_bounds_controls_and_trim');
 const rows=normalizeOnlineLocations(doc());same(Object.keys(rows[0]),['name','secondaryLabel','lat','lon','source'],'normalized whitelist');assert(Object.isFrozen(rows[0])&&rows[0].lat===A.lat,'numeric immutable');cases.push('provider_metadata_removed_numeric_coordinates');
 const poi=doc();poi.features[0].properties={name:['Château'],city:['Versailles'],postcode:['78000']};assert(normalizeOnlineLocations(poi)[0].name==='Château','array names');cases.push('address_and_named_place_shape');
 const duplicates=doc();duplicates.features.push(duplicates.features[0]);same(normalizeOnlineLocations(duplicates).length,1,'dedup');cases.push('bounded_deduplicated_results');
 for(const value of[{}, {type:'FeatureCollection',features:[{geometry:{type:'Point',coordinates:[2,91]},properties:{name:'Invalid'}}]}, {type:'FeatureCollection',features:Array(101).fill({})}])await rejects(()=>normalizeOnlineLocations(value));cases.push('malformed_or_invalid_coordinates_rejected');
 same(normalizeOnlineLocations({type:'FeatureCollection',features:[]}),[],'empty');cases.push('zero_results');
 let calls=[];const client=createLocationSearch({config,localSearch:noLocal,intervalMs:0,fetcher:async(url,options)=>{calls.push({url,options});return response(doc())}});
 await rejects(()=>client.searchResolvedLocations('x'));assert(!calls.length,'invalid no request');cases.push('invalid_query_never_fetches');
 const result=await client.searchResolvedLocations('Grand Trianon');assert(result.remote[0].name===A.name&&calls.length===1,'one fetch');const req=calls[0];const query=new URL(req.url).searchParams;
 same([...query.keys()],['q','index','limit'],'query only');assert(req.options.credentials==='omit'&&req.options.referrerPolicy==='no-referrer'&&req.options.redirect==='error'&&req.options.cache==='no-store','privacy');cases.push('explicit_operation_one_fetch_query_only_no_credentials');
 const localOnly=createLocationSearch({config,localSearch:async()=>({available:true,results:[{...A,secondaryLabel:'Local',source:'local'}]}),online:()=>false,fetcher:()=>{throw Error('must not fetch')}});
 const offline=await localOnly.searchResolvedLocations('Trianon');assert(offline.local.length===1&&offline.remoteMessage.includes('offline'),'offline local survives');cases.push('offline_local_works_remote_fails_cleanly');
 const unavailable=createLocationSearch({config:()=>({available:false}),localSearch:noLocal,fetcher:()=>{throw Error('no fetch')}});assert((await unavailable.searchResolvedLocations('abc')).remoteMessage.includes('unavailable'),'disabled');cases.push('provider_unavailable');
 for(const [name,r] of[['http',new Response('',{status:503})],['rate_limit',new Response('',{status:429,headers:{'Retry-After':'5'}})],['malformed',response({bad:true})],['invalid_json',new Response('{')]]){
 const c=createLocationSearch({config,localSearch:noLocal,fetcher:async()=>r});const r2=await c.searchResolvedLocations('abc');assert(r2.remote.length===0&&r2.remoteMessage&&!r2.remoteMessage.includes('{'),'clean failure');cases.push(name+'_clear_failure');}
 const timeout=createLocationSearch({config,localSearch:noLocal,timeoutMs:20,fetcher:(_,o)=>new Promise((_,reject)=>o.signal.addEventListener('abort',()=>reject(o.signal.reason),{once:true}))});assert((await timeout.searchResolvedLocations('abc')).remoteMessage.includes('timed out'),'timeout');cases.push('bounded_timeout');
 let started=false,aborted=false;const aborter=createLocationSearch({config,localSearch:noLocal,fetcher:(_,o)=>new Promise((_,reject)=>{started=true;o.signal.addEventListener('abort',()=>{aborted=true;reject(o.signal.reason)},{once:true})})});const control=new AbortController();const pending=aborter.searchResolvedLocations('abc',{signal:control.signal});await until(()=>started);control.abort();await rejects(()=>pending);assert(aborted,'fetch aborted');cases.push('abort_propagates_to_fetch');
 let inFlight=0,maxFlight=0,firstResolve,firstStarted=false;const serial=createLocationSearch({config,localSearch:noLocal,intervalMs:0,fetcher:async()=>{inFlight++;maxFlight=Math.max(maxFlight,inFlight);if(!firstStarted){firstStarted=true;await new Promise(r=>firstResolve=r)}inFlight--;return response(doc(firstStarted?B:A))}});
 const old=serial.searchResolvedLocations('first');const rejected=old.catch(()=>true);await until(()=>firstStarted);const latest=serial.searchResolvedLocations('second');await sleep(20);assert(maxFlight===1,'one flight');firstResolve();assert(await rejected===true,'obsolete rejected');assert((await latest).remote[0].name===B.name&&maxFlight===1,'latest');cases.push('obsolete_response_rejected_single_remote_flight');
 const fixture=await(await fetch('../fixtures/pr40_regional_data.json')).json();const data=createLocalRegionData(fixture.manifest,fixture);const feature=fixture.pois.features.find(f=>!['private','restricted'].includes(f.access_status)&&f.potability!=='non_potable');const matches=data.searchPlaceNames(feature.display_name);assert(matches.available&&matches.results.some(r=>r.lat===feature.coordinate.lat&&r.lon===feature.coordinate.lon),'stored coordinates');cases.push('local_loaded_index_name_search_real_coordinates');
 const normalizedQuery=feature.display_name.normalize('NFD').replace(/\p{M}/gu,'').toUpperCase();assert(data.searchPlaceNames(normalizedQuery).results.length,'accent case');cases.push('local_deterministic_accent_case_normalization');
 const all=data.searchPlaceNames('water');assert(all.results.every(r=>!fixture.pois.features.some(f=>f.coordinate.lat===r.lat&&f.coordinate.lon===r.lon&&(['private','restricted'].includes(f.access_status)||f.potability==='non_potable'))),'hidden data');cases.push('local_private_restricted_nonpotable_excluded');
 let lease=false;const searchLocal=createLocalPlaceNameSearch({versions:{withCommittedRegions:async f=>{lease=true;try{return await f([{status:'committed',region_id:fixture.manifest.region_id,manifest:fixture.manifest}])}finally{lease=false}},committedDirectory:async()=>({})},regionClient:{loadVersion:async()=>({identity:data.identity,searchPlaceNames:q=>{assert(lease,'lease held');return data.searchPlaceNames(q)}})},selectedRegionId:()=>fixture.manifest.region_id});await searchLocal(feature.display_name);assert(!lease,'released');cases.push('local_query_reuses_committed_read_lease');
 const storageRoot=await navigator.storage.getDirectory(),folder='name-search-'+crypto.randomUUID();const ownedRoot=await storageRoot.getDirectoryHandle(folder,{create:true});const versions=createRegionVersionStore({storage:{getDirectory:async()=>ownedRoot},locks:navigator.locks});const worker=createLocalRegionClient();
 try{
 const download=await distribution(fixture,'Name search fixture');const ticket=await versions.stage(JSON.stringify(download.manifest));
 const scoped=(manifest,directory)=>createVersionedRegionComponents({manifest,directory,fetchResource:async url=>new Response(download.files.get(new URL(url).pathname.slice(1))),pageLocation:location});
 await versions.withStagedVersion(ticket,async({manifest,directory})=>{const components=await scoped(manifest,directory);await components.installMap(location.origin+'/manifest.json');await components.installIndexes(location.origin+'/manifest.json')});
 await versions.activate(ticket,{verifyComponent:async(kind,manifest,directory)=>kind==='routing'?true:kind==='map'?(await scoped(manifest,directory)).verifyMap():(await scoped(manifest,directory)).verifyIndexes()});
 const query=createLocalPlaceNameSearch({versions,selectedRegionId:()=>download.manifest.region_id,regionClient:{loadVersion:(...args)=>worker.loadPlacesVersion(...args)}});
 const realRows=await query(feature.display_name);assert(realRows.results.length,'worker name query');cases.push('real_opfs_worker_lease_name_search');
 const directory=await versions.committedDirectory(download.manifest.region_id,download.manifest.build_id),components=await directory.getDirectoryHandle('sugarglider-region-components'),region=await components.getDirectoryHandle(download.manifest.region_id),version=await region.getDirectoryHandle(download.manifest.build_id),nature=await version.getDirectoryHandle('nature'),file=await nature.getFileHandle('index.json.gz');const bytes=new Uint8Array(await(await file.getFile()).arrayBuffer());bytes[bytes.length-1]^=1;const writable=await file.createWritable();await writable.write(bytes);await writable.close();
 await rejects(()=>worker.loadVersion(download.manifest,directory));cases.push('existing_full_index_loader_still_rejects_corrupt_nature');
 assert((await query(feature.display_name)).results.length,'valid Places independent');cases.push('verified_places_names_survive_unrelated_invalid_nature');
 }finally{worker.close();await storageRoot.removeEntry(folder,{recursive:true})}
 const html=await(await fetch('../../src/sugarglider/web/static/index.html')).text();root=new DOMParser().parseFromString(html,'text/html').querySelector('#location-search-dialog');document.body.append(root);
 let selections=[],focusReturns=0;const dialog=initializeLocationSearchDialog({root,search:(...a)=>client.searchResolvedLocations(...a),config,canEdit:()=>true,onSelect:(target,p)=>{selections.push({target,p});return true},restoreFocus:()=>focusReturns++});const el=id=>root.querySelector('#location-search-'+id);
 dialog.open();const beforeTyping=calls.length;el('query').value='Grand Trianon';el('query').dispatchEvent(new InputEvent('input',{bubbles:true}));await sleep(20);assert(calls.length===beforeTyping,'typing no calls');cases.push('dialog_typing_zero_remote_requests');
 el('form').requestSubmit();await until(()=>el('online').querySelector('button'));assert(calls.length===beforeTyping+1,'submit one request');assert(document.activeElement===el('online').querySelector('button'),'result focus');cases.push('dialog_submit_one_request_result_focus');
 assert(el('online').querySelector('li')&&el('query').labels.length&&root.getAttribute('aria-labelledby'),'semantic labels');cases.push('dialog_semantic_results_and_labels');
 el('online').querySelector('button').click();await until(()=>!root.open&&focusReturns);same(selections[0].p,A,'select whitelist');cases.push('result_selection_only_name_lat_lon_focus_restoration');
 const evil={name:'<img src=x onerror=alert(1)>',lat:A.lat,lon:A.lon};const unsafe=createLocationSearch({config,localSearch:noLocal,intervalMs:0,fetcher:async()=>response(doc(evil))}); root.remove();root=new DOMParser().parseFromString(html,'text/html').querySelector('#location-search-dialog');document.body.append(root);
 const evilDialog=initializeLocationSearchDialog({root,search:(...a)=>unsafe.searchResolvedLocations(...a),config,canEdit:()=>true,onSelect:()=>false});evilDialog.open();root.querySelector('input').value='unsafe';root.querySelector('form').requestSubmit();await until(()=>root.querySelector('#location-search-online button'));assert(!root.querySelector('img')&&root.textContent.includes('<img'),'inert');cases.push('unsafe_provider_text_rendered_inert');root.close();await sleep(0);
 let closeAbort=false;const slow=createLocationSearch({config,localSearch:noLocal,fetcher:(_,o)=>new Promise((_,reject)=>o.signal.addEventListener('abort',()=>{closeAbort=true;reject(o.signal.reason)},{once:true}))});root.remove();root=new DOMParser().parseFromString(html,'text/html').querySelector('#location-search-dialog');document.body.append(root);const slowDialog=initializeLocationSearchDialog({root,search:(...a)=>slow.searchResolvedLocations(...a),config,canEdit:()=>true,onSelect:()=>false});slowDialog.open();root.querySelector('input').value='slow';root.querySelector('form').requestSubmit();await sleep(30);root.querySelector('#location-search-close').click();await until(()=>closeAbort);cases.push('dialog_close_aborts_pending_search');
 const reset=()=>{Object.assign(state,structuredClone(initial));state.routingProfile='trail_run';clearPointUndo()};const endpoints=()=>state.planningMode==='auto_tour'?state.autoTour:state.waypointEndpoints;
 const assign=(kind,p)=>{saveActivePoints();assignRouteEndpoint(endpoints(),kind,p);if(state.planningMode==='auto_tour'&&kind==='start')state.points=[p,...state.autoTour.hardPoints].filter(Boolean)};
 const add=p=>addResolvedRouteLocation(p,{assignEndpoint:assign});const move=(target,p)=>replaceResolvedRouteLocation(target,p,{assignEndpoint:assign});
 for(const scenario of['start','loop_stop','open_end','moved_interior']){
 const build=location=>{reset();if(scenario==='open_end')changeMapTopology('point_to_point');if(scenario==='start')add(location);else{add(A);if(scenario==='moved_interior'){add(C);move({index:0},location)}else add(location)}return currentPlanRequest()};
 const direct=build(B),searched=build({...normalizeOnlineLocations(doc(B))[0],query:'ignored',provider:'ignored'});same(direct,searched,'canonical '+scenario);window.searchCanonicalEvidence.push({scenario,direct,searched,equal:true});cases.push('canonical_equivalence_'+scenario);
 assert(!JSON.stringify(searched).includes('ignored')&&!('source' in endpoints().start),'metadata absent');}
 reset();add(A);assert(undoPointEdit()&&!endpoints().start,'undo empty');assert(!undoPointEdit(),'exactly one');assert(redoPointEdit()&&endpoints().start.name===A.name,'redo start');cases.push('add_start_one_undo_redo');
 add(B);assert(undoPointEdit(),'stop undo');assert(redoPointEdit()&&state.points[0].name===B.name,'stop redo');cases.push('append_stop_undo_redo');
 state.points[0]={...state.points[0],id:'imported',constraintStrength:'approach',itineraryReason:'See the castle',accessSearchRadiusM:333};const original=structuredClone(state.points[0]);clearPointUndo();move({index:0},C);assert(state.points[0].id===original.id&&state.points[0].itineraryReason===original.itineraryReason&&state.points[0].constraintStrength===original.constraintStrength&&state.selectedPointIndex===0,'identity constraints');assert(undoPointEdit(),'move undo');same(state.points[0],original,'restore coord name');assert(!undoPointEdit(),'one move edit');redoPointEdit();assert(state.points[0].name===C.name,'move redo');cases.push('move_interior_preserves_identity_constraints_reason_selection_one_history');
 const count=state.points.length;move({endpoint:'start'},B);assert(state.points.length===count&&endpoints().start.name===B.name&&state.selectedEndpointKind==='start','start');cases.push('move_start_no_stop');
 reset();changeMapTopology('point_to_point');add(A);add(B);move({endpoint:'end'},C);assert(endpoints().end.name===C.name&&state.points.length===0,'end');cases.push('move_end_preserves_topology');
 undoPointEdit();add(A);assert(!redoPointEdit(),'new edit clears redo');cases.push('new_edit_after_undo_clears_redo');
 state.generationResult={candidates:[]};state.generationSourceRequest=currentPlanRequest();move({endpoint:'start'},C);invalidateCandidates();assert(!state.generationResult&&!state.generationSourceRequest&&state.resultsInvalidated,'invalidated');cases.push('selection_invalidates_old_candidates_no_routing_module');
 const unchanged=currentPlanRequest();await client.searchResolvedLocations('just search');same(currentPlanRequest(),unchanged,'search no mutation');cases.push('search_alone_never_changes_route_intent');
}finally{root?.remove();Object.assign(state,initial);clearPointUndo()}return cases}
