// Real immutable Yvelines bytes, live IGN query, isolated browser OPFS; no device action.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const O=process.env.SEARCH_EVIDENCE_DIR,B=process.env.SEARCH_BASE_URL||'http://127.0.0.1:8850',BEFORE=process.env.SEARCH_BASELINE_URL||'http://127.0.0.1:8851';
if(!O)throw Error('Set SEARCH_EVIDENCE_DIR outside Git');
const sizes=[['phone390',390,844],['phone360',360,800],['phone412',412,915],['short',390,420],['text200',390,844],['desktop1280',1280,800],['desktop1440',1440,900]];
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',args:['--no-sandbox','--enable-unsafe-swiftshader']});const results=[];try{
for(const[name,width,height]of sizes.filter(v=>!process.env.VIEW_FILTER||v[0]===process.env.VIEW_FILTER||process.env.VIEW_FILTER==='other'&&v[0]!=='phone390')){
 const c=await browser.newContext({viewport:{width,height},isMobile:width<500,hasTouch:width<500,serviceWorkers:'block',reducedMotion:'reduce'}),p=await c.newPage();p.setDefaultTimeout(30000);const checks=[],errors=[],requests=[];let routeCalls=0;const record=s=>{checks.push(s);console.log(name,s)};
 p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.url().startsWith('https://data.geopf.fr/geocodage/search'))requests.push({url:r.url(),method:r.method(),headers:r.headers()});if(/\/v2\/plans\/(generate|reverse)$/.test(r.url()))routeCalls++});
 await c.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname==='127.0.0.1'||u.origin==='https://data.geopf.fr'&&u.pathname==='/geocodage/search')return r.continue();return r.abort()});
 await p.addInitScript(()=>{window.searchOnline=false;Object.defineProperty(navigator,'onLine',{get:()=>window.searchOnline})});
 await p.goto(B+'/setup');await p.evaluate(async()=>{
 const{createMapPackStore}=await import('/static/map_pack_store.js');await createMapPackStore().installPack(location.origin+'/pack/map/manifest.json');
 const{openPwaStore,PWA_STORES}=await import('/static/pwa_store.js');const store=await openPwaStore();await store.put(PWA_STORES.trailProfile,'current',{schema_version:1,display_name:'Search acceptance',avatar_key:'forest'});store.close();
 // Snapshot a previously installed index in this disposable browser. All seven
 // source component files remain immutable; no native routing installation or
 // normal installer success is claimed (real nature document is invalid).
 const manifest=await(await fetch('/pack/manifest.json')).json(),{createRegionVersionStore}=await import('/static/region_versions.js');const versions=createRegionVersionStore();const ticket=await versions.stage(JSON.stringify(manifest));
 await versions.withStagedVersion(ticket,async({directory})=>{
 const root=await directory.getDirectoryHandle('sugarglider-region-components',{create:true}),region=await root.getDirectoryHandle(manifest.region_id,{create:true}),version=await region.getDirectoryHandle(manifest.build_id,{create:true});
 const write=async(d,n,b)=>{const w=await(await d.getFileHandle(n,{create:true})).createWritable();await w.write(b);await w.close()};
 await write(version,'manifest.json',JSON.stringify(manifest));
 for(const kind of['pois','nature']){const bytes=await(await fetch('/pack/'+manifest.components[kind].files[0].path)).arrayBuffer();const{verifyRegionalBytes}=await import('/static/regional_manifest.js');await verifyRegionalBytes(bytes,manifest.components[kind].files[0]);await write(await version.getDirectoryHandle(kind,{create:true}),'index.json.gz',bytes)}
 await write(region,'active.json',JSON.stringify({build_id:manifest.build_id}));
 });
 await versions.activate(ticket,{verifyComponent:async(kind,m,d)=>{if(['pois','nature'].includes(kind))return(await(await import('/static/region_components.js')).createVersionedRegionComponents({manifest:m,directory:d})).verifyIndexes();return true}});
 });
 await p.goto(B+'/');await p.evaluate(async()=>{window.S=await import('/static/state.js');window.M=await import('/static/map.js')});await p.waitForFunction(()=>window.S.state.config&&document.querySelectorAll('#profile option').length===6);
 if(name==='text200')await p.evaluate(()=>document.documentElement.style.fontSize='32px');
 const req=()=>p.evaluate(()=>window.S.currentPlanRequest()),snap=label=>p.screenshot({path:path.join(O,'screenshots',name+'-'+label+'.png')});
 const view=async v=>{const t=p.locator(`[data-shell-view="${v}"]`);if(await t.isVisible())await t.click();await p.waitForTimeout(80)};
 async function open(target){await view('map');if(target){const chip=p.locator(`[data-route-chip="${target}"]`);if(await chip.getAttribute('aria-pressed')!=='true')await chip.click();await p.locator('[data-dock-action="move"]').click();await p.locator('[data-dock-action="move-search"]').click()}else{await p.locator('#dock-add').click();await p.locator('[data-dock-action="search-location"]').click()}await p.waitForFunction(()=>document.querySelector('#location-search-dialog').open);assert.equal(await p.evaluate(()=>document.activeElement.id),'location-search-query')}
 async function query(text){await p.locator('#location-search-query').fill(text);await p.locator('#location-search-query').press('Enter');await p.waitForFunction(()=>document.querySelector('#location-search-results').getAttribute('aria-busy')==='false');}
 // Core local workflow is tested with actual network disabled and stored coordinates.
 await open();await query('Lartecono');assert(await p.locator('#location-search-local button').count()>0,'Local worker initializes from installed bytes');await p.locator('#location-search-close').click();await p.waitForTimeout(50);
 await c.setOffline(true);await p.waitForTimeout(500);await open();const beforeTyping=requests.length;await p.locator('#location-search-query').fill('Lartecono');await p.waitForTimeout(150);assert.equal(requests.length,beforeTyping);record('typing makes zero remote requests');
 await p.locator('#location-search-query').press('Enter');await p.waitForFunction(()=>document.querySelector('#location-search-results').getAttribute('aria-busy')==='false');assert.equal(await p.locator('#location-search-local button').count(),1);assert((await p.locator('#location-search-error').innerText()).includes('offline'));await snap('local-offline-results');
 const layout=await p.locator('#location-search-dialog').evaluate(d=>{const r=d.getBoundingClientRect(),b=d.querySelector('.location-search-body'),close=d.querySelector('header button').getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,closeTop:close.top,closeBottom:close.bottom,scrollHeight:b.scrollHeight,clientHeight:b.clientHeight,overflow:document.documentElement.scrollWidth>innerWidth,horizontal:b.scrollWidth>b.clientWidth}});
 assert(!layout.overflow&&!layout.horizontal&&layout.x>=0&&layout.width<=width&&layout.y>=0&&layout.closeBottom<=height);assert(await p.locator('#location-search-local button').evaluate(b=>b.getBoundingClientRect().height>=44));assert(await p.locator('#location-search-query').evaluate(e=>e.labels.length===1));record('responsive scroll, visible Close, meaningful semantic results, touch targets, no horizontal overflow');
 await p.locator('#location-search-local button').click();await p.waitForFunction(()=>!document.querySelector('#location-search-dialog').open);const start=await req();assert.equal(start.start.name,'Lartecono');assert.equal(start.start.lat,48.8008765);assert.equal(start.start.lon,2.1251258);assert.equal(start.kind,'auto_tour');record('offline real Lartecono selection becomes Start at stored coordinate');
 await p.locator('#undo-point-edit').click();assert.equal(await p.evaluate(()=>window.S.state.autoTour.start),null);await p.locator('#redo-point-edit').click();assert.deepEqual(await req(),start);record('Start Undo to empty / Redo exact');
 await open();await query('Sweet Josie');await p.locator('#location-search-local button').click();const loop=await req();assert.equal(loop.kind,'waypoint_route');assert.equal(loop.waypoints[0].coordinate.name,'Sweet Josie');record('second search selection appends loop stop through existing automatic grammar');
 await p.evaluate(()=>{window.S.state.generationResult={candidates:[]};window.S.state.generationSourceRequest=window.S.currentPlanRequest()});
 await open('0');await query('Orangerie');await snap('move-search-results');await p.locator('#location-search-local button').filter({hasText:'Orangerie'}).first().click();const moved=await req();assert(!await p.evaluate(()=>window.S.state.generationResult||window.S.state.generationSourceRequest));assert.equal(moved.waypoints.length,1);assert.notDeepEqual(moved.waypoints[0].coordinate,loop.waypoints[0].coordinate);await p.locator('#undo-point-edit').click();assert.deepEqual(await req(),loop);await p.locator('#redo-point-edit').click();assert.deepEqual(await req(),moved);record('Move replaces coordinate/name; one Undo / Redo restores exact request');
 await p.locator('#dock-finish').selectOption('point_to_point');const promoted=await req();assert.equal(promoted.waypoints.length,0);assert.deepEqual(promoted.end,moved.waypoints[0].coordinate);
 await open();await query('Sweet Josie');await p.locator('#location-search-local button').click();const extended=await req();assert.equal(extended.waypoints.length,1);assert.deepEqual(extended.waypoints[0].coordinate,promoted.end);assert.equal(extended.end.name,'Sweet Josie');record('open-route search extends End and retains old End as stop');
 for(const target of['start','end']){const prior=await req();await open(target);await query(target==='start'?'Sweet Josie':'Lartecono');await p.locator('#location-search-local button').click();const after=await req();assert.equal(after.waypoints.length,prior.waypoints.length);assert.equal(after[target].name,target==='start'?'Sweet Josie':'Lartecono');await p.locator('#undo-point-edit').click();assert.deepEqual(await req(),prior)}record('Move Start and End create no stops and each Undo is exact');
 await open();const cancelBefore=await req();await p.locator('#location-search-query').fill('1 Place d Armes Versailles');await p.keyboard.press('Escape');assert.deepEqual(await req(),cancelBefore);assert.equal(routeCalls,0);record('search/cancel never mutates intent; no automatic generation or reversal');
 // Restore connectivity after modal closes; one live query on the principal phone.
 const beforeReconnect=await req();await p.evaluate(()=>window.searchOnline=true);await c.setOffline(false);await p.waitForTimeout(800);await p.evaluate(async()=>{window.S=await import('/static/state.js');window.M=await import('/static/map.js');window.searchOnline=true});await p.waitForFunction(()=>window.S.state.config);
 if(!await p.evaluate(()=>window.S.state.autoTour.start||window.S.state.waypointEndpoints.start)){await p.locator('#request-file').setInputFiles({name:'acceptance-plan.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(beforeReconnect))});await p.waitForFunction(()=>window.S.state.waypointEndpoints.start);record('existing reconnect reload restored by explicit canonical import in acceptance fixture')}
 if(name==='phone390'){
 await open('start');const before=requests.length;await query("1 place d'Armes Versailles");assert.equal(requests.length,before+1);assert(await p.locator('#location-search-online button').count()>0);const u=new URL(requests.at(-1).url);assert.deepEqual([...u.searchParams.keys()],['q','index','limit']);assert.equal(u.searchParams.get('q'),"1 place d'Armes Versailles");assert(!requests.at(-1).headers.cookie&&!requests.at(-1).headers.authorization&&!requests.at(-1).headers.referer);await snap('live-address-results');await p.locator('#location-search-online button').first().focus();await p.keyboard.press('ArrowDown');await p.keyboard.press('ArrowUp');await p.keyboard.press('Enter');const onlineIntent=await req();assert.equal(onlineIntent.start.lat,48.803725);assert.equal(onlineIntent.start.lon,2.124426);assert.equal(onlineIntent.start.name,"1 Place d'Armes");record('one real IGN query; query-only no credentials/referrer; keyboard selects normalized numeric address');
 }
 // Real ordinary map POIs remain inspection-only.
 await view("map");const beforePoi=await req();for(const[id,lon,lat]of[['node/2479030759',2.1329326,48.8067453],['node/2421490186',2.1240874,48.8040423]]){
 await p.evaluate(([lon,lat])=>window.M.focusCoordinate([lon,lat]),[lon,lat]);await p.locator('.maplibregl-ctrl-zoom-in').click({clickCount:2});await p.waitForTimeout(350);await p.evaluate(([lon,lat])=>window.M.keepCoordinateVisible([lon,lat]),[lon,lat]);await p.waitForFunction(id=>window.M.placeMapDiagnostics().markerIds.includes(id),id);await p.waitForTimeout(700);
 const xy=await p.evaluate(id=>window.M.placeMapDiagnostics().positions.find(f=>f.id===id)?.point,id);assert(xy,'POI position');const r=await p.locator('#map .maplibregl-canvas').boundingBox();console.log(name,'map POI',id,xy,await p.evaluate(([x,y])=>({hit:document.elementFromPoint(x,y)?.className,dock:document.querySelector('#route-dock').getBoundingClientRect().top}),[r.x+xy[0],r.y+xy[1]]));await p.mouse.click(r.x+xy[0],r.y+xy[1]);await p.waitForFunction(id=>window.S.state.selectedPoiId===id,id);assert.deepEqual(await req(),beforePoi);await snap(id.includes('247903')?'ice-inspection':'water-inspection');await p.locator('.priority-place-popup .maplibregl-popup-close-button').click();}
 record('real ice-cream and verified-water map taps inspect only');assert(await p.locator('.maplibregl-ctrl-attrib').innerText().then(t=>t.includes('OpenStreetMap')));
 if(name==='phone390'){
 // Same canonical coordinate intents must route/export identically to exact main.
 const canonical=await req();canonical.end={name:'End',lat:48.790122,lon:2.118049};canonical.waypoints=[{...canonical.waypoints[0],coordinate:{name:'Middle',lat:48.786583,lon:2.105706}}];canonical.start={name:'Start',lat:48.798432,lon:2.122484};canonical.distance_objective.target_m=8000;canonical.candidate_count=2;
 for(const topology of['loop','point_to_point']){const request={...canonical,topology:topology,end:topology==='loop'?null:canonical.end};const a=await c.request.post(B+'/v2/plans/generate',{data:request,timeout:240000}),z=await c.request.post(BEFORE+'/v2/plans/generate',{data:request,timeout:240000});assert.equal(a.status(),200,await a.text());assert.equal(z.status(),200,await z.text());const current=await a.json(),base=await z.json();const signature=r=>r.candidates.map(c=>({id:c.id,rank:c.rank,roles:c.roles,order:c.actual_waypoint_order,geometry:c.route.geometry,traversal:c.traversal}));assert.deepEqual(signature(current),signature(base));let exports=[];
 for(const candidate of current.candidates){const original=base.candidates.find(c=>c.id===candidate.id);const gpx=await p.evaluate(async c=>{const e=(await import('/static/local_gpx_client.js')).createLocalGpxExporter();try{return await(await e.exportCandidate(c)).blob.text()}finally{e.close?.()}},candidate);const prior=await c.newPage();await prior.goto(BEFORE+'/setup');const old=await prior.evaluate(async c=>{const e=(await import('/static/local_gpx_client.js')).createLocalGpxExporter();try{return await(await e.exportCandidate(c)).blob.text()}finally{e.close?.()}},original);await prior.close();assert.equal(gpx,old);assert(!gpx.includes('<rte>')&&!gpx.includes('<extensions>'));fs.writeFileSync(path.join(O,'runtime',topology+'-'+candidate.id+'.gpx'),gpx);exports.push({id:candidate.id,gpxEqual:true})}
 fs.writeFileSync(path.join(O,'runtime','routing-'+topology+'.json'),JSON.stringify({request,current,baseline:base,exports},null,2));record(topology+': exact main candidate IDs/order/rank/roles/geometry/traversal and every GPX byte equal');}
 }
 assert.equal(errors.length,0,errors.join('\n'));results.push({name,width,height,checks,layout,requests,routeCalls,errors});fs.writeFileSync(path.join(O,'runtime','acceptance-results'+(process.env.VIEW_FILTER?'-'+process.env.VIEW_FILTER:'')+'.json'),JSON.stringify(results,null,2));await c.close();
}}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
