import {layers,namedFlavor} from '../../src/sugarglider/web/static/vendor/protomaps-basemaps-5.7.2/basemaps.js';
import {offlineBasemapPresentationLayer} from '../../src/sugarglider/web/static/offline_label_policy.js';
import {isPriorityPlace,placePresentation} from '../../src/sugarglider/web/static/place_presentation.js';
import {initializeMap,renderPois,placeMapDiagnostics,mapPresentationDiagnostics} from '../../src/sugarglider/web/static/map.js';
const assert=(v,m)=>{if(!v)throw Error(m)};
const equal=(a,b,m)=>assert(JSON.stringify(a)===JSON.stringify(b),m);
const until=async p=>{for(let i=0;i<300;i++){if(p())return;await new Promise(r=>setTimeout(r,25))}throw Error('Timed out')};
export async function run(){
 const cases=[];const generated=layers('local',namedFlavor('light'),{lang:'fr'});
 const labels=generated.map(offlineBasemapPresentationLayer).filter(l=>l?.type==='symbol');
 equal(labels.map(l=>l.id).sort(),['earth_label_islands','places_locality','places_subplace','roads_labels_major','roads_labels_minor','water_label_lakes','water_label_ocean','water_waterway_label'].sort(),'Useful families only');
 for(const l of labels){assert(!Object.keys({...l.layout,...l.paint}).some(k=>k.startsWith('icon-')),'No sprite fields');equal(l.layout['text-font'],['Open Sans Semibold'],'Bundled font');assert(!JSON.stringify(l.layout['text-field']).includes('Noto'),'No formatted font overrides');assert(!l.layout['text-allow-overlap'],'Collision labels')}
 assert(!offlineBasemapPresentationLayer({id:'future_shop',type:'symbol'}),'Future symbols default excluded');assert(!offlineBasemapPresentationLayer({type:'background'}),'Background has no vector source');cases.push('eight_useful_families_unknown_symbols_excluded_icon_fields_removed_local_font');
 for(const [category,potability,expected] of [['drinking_water','verified',true],['drinking_water','unknown',false],['drinking_water','non_potable',false],['fountain','verified',false],['water_tap','unknown',false],['ice_cream','not_applicable',true],['viewpoint','not_applicable',false]])equal(isPriorityPlace({category,potability}),expected,'Exact promotion '+category+potability);
 cases.push('priority_classification_requires_verified_drinking_water_or_ice_cream');
 const features=[['water','drinking_water','verified'],['ice','ice_cream','not_applicable'],['unknown','fountain','unknown'],['bad','drinking_water','non_potable'],['scenic','viewpoint','not_applicable']].map(([id,category,potability],i)=>({id,category,potability,display_name:id,coordinate:{lat:.01+i*.0005,lon:.01},tags:[],access_status:'public'}));
 let ready=false,selected=null,placements=0;const choose=id=>{selected=id;renderPois(features,id,choose,{onDeselect:()=>choose(null)})};
 initializeMap({initial_center:[.01,.011],initial_zoom:12,offline_mode:true},{onReady:()=>{ready=true;choose(null)},onMapClick:()=>placements++,onError:m=>{throw Error(m)}});
 await until(()=>ready&&placeMapDiagnostics().priorityMarkerIds.length===1);
 const d=mapPresentationDiagnostics();assert(d.glyphs.startsWith(location.origin+'/static/fonts/'),'Local glyph URL');assert(!Object.values(d.sources).some(s=>s.type==='raster'),'Offline has no raster');assert(!d.sources['places-priority-pois'].cluster,'Unclustered priority');equal(d.sources['places-pois'].cluster,true,'Generic clusters kept');equal(d.sources['places-pois'].data.features.map(f=>f.id),['unknown','bad','scenic'],'Exact generic membership');equal(d.sources['places-priority-pois'].data.features.map(f=>f.id),['ice'],'Ice appears at z12; water waits for z13');equal(placeMapDiagnostics().priorityLabelIds,[],'Names absent at z12');cases.push('z12_ice_priority_icons_generic_membership_truthful_clusters_no_early_names');
 document.querySelector('.maplibregl-ctrl-zoom-in').click();await until(()=>placeMapDiagnostics().priorityMarkerIds.length===2);equal(mapPresentationDiagnostics().sources['places-priority-pois'].data.features.map(f=>f.id),['water','ice'],'Water visible from z13');cases.push('z13_water_priority_visible_without_duplicate_cluster');
 for(const id of ['water','ice']){const point=placeMapDiagnostics().positions.find(f=>f.id===id).point;const c=document.querySelector('canvas'),r=c.getBoundingClientRect();for(const type of ['mousedown','mouseup','click'])c.dispatchEvent(new MouseEvent(type,{bubbles:true,clientX:r.x+point[0],clientY:r.y+point[1],button:0,buttons:type==='mousedown'?1:0}));await until(()=>selected===id);equal(placements,0,'Inspect does not place');await until(()=>placeMapDiagnostics().selectedMarkerIds.includes(id));assert(!mapPresentationDiagnostics().sources['places-priority-pois'].data.features.some(f=>f.id===id),'Selected removed from priority');document.querySelector('.maplibregl-popup-close-button').click();await until(()=>placeMapDiagnostics().priorityMarkerIds.includes(id))}
 cases.push('real_map_water_and_ice_inspect_only_selected_deduplicated');
 document.querySelector('.maplibregl-ctrl-zoom-in').click();await until(()=>mapPresentationDiagnostics().sources['places-priority-pois'].data.features.find(f=>f.id==='water')?.properties.show_label===true);equal(mapPresentationDiagnostics().sources['places-priority-pois'].data.features.find(f=>f.id==='ice').properties.show_label,false,'Ice names wait at z14');cases.push('z14_water_names_ice_names_wait_collision_placed');
 document.querySelector('.maplibregl-ctrl-zoom-in').click();await until(()=>mapPresentationDiagnostics().sources['places-priority-pois'].data.features.find(f=>f.id==='ice')?.properties.show_label===true);cases.push('z15_ice_names_visible');
 equal(placePresentation(features[1]).minZoom,12,'Ice planning zoom');
 document.querySelector('#map').style.height='300px';document.documentElement.style.fontSize='32px';
 const dock=document.createElement('div');dock.id='route-dock';dock.style.cssText='position:absolute;top:230px;left:0;width:900px;height:70px';document.body.append(dock);
 ready=false;initializeMap({initial_center:[.01,.011],initial_zoom:15,offline_mode:true},{onReady:()=>{ready=true;choose('water')},onMapClick:()=>placements++,onError:m=>{throw Error(m)}});
 await until(()=>ready&&placeMapDiagnostics().selectedMarkerIds.includes('water'));
 for(const id of ['water','ice']){choose(id);await until(()=>placeMapDiagnostics().selectedMarkerIds.includes(id));const popup=document.querySelector('.priority-place-popup'),card=popup.getBoundingClientRect(),mapRect=document.querySelector('canvas').getBoundingClientRect();assert(card.top>=mapRect.top+11,'Short popup stays in map');assert(card.bottom<=dock.getBoundingClientRect().top-20,'Short popup clears dock');const close=popup.querySelector('.maplibregl-popup-close-button').getBoundingClientRect();assert(close.width>=44&&close.height>=44,'Close remains usable');const content=popup.querySelector('.point-popup,.place-details');assert(content.scrollHeight>content.clientHeight,'Long details scroll instead of clipping');}
 equal(placements,0,'Sizing never places points');cases.push('short_map_200_percent_priority_details_scroll_above_dock_close_accessible');return cases;
}
