import {createLocalRegionData,eligibleLocalPoi} from '../../src/sugarglider/web/static/local_region_data.js';
import {createLocalRegionClient} from '../../src/sugarglider/web/static/local_region_client.js';
import {createRegionVersionStore} from '../../src/sugarglider/web/static/region_versions.js';
import {createVersionedRegionComponents} from '../../src/sugarglider/web/static/region_components.js';
import {createLocalPlaceSearch} from '../../src/sugarglider/web/static/local_places.js';
import {parseRegionalManifest} from '../../src/sugarglider/web/static/regional_manifest.js';
import {placeCompatibilityMessage} from '../../src/sugarglider/web/static/place_capabilities.js';
import {PLACE_PRESENTATIONS,isPriorityPlace} from '../../src/sugarglider/web/static/place_presentation.js';
import {state,saveActivePoints,assignRouteEndpoint,currentPlanRequest} from '../../src/sugarglider/web/static/state.js';
import {resolvedPoiLocation} from '../../src/sugarglider/web/static/poi_route_location.js';
import {addResolvedRouteLocation} from '../../src/sugarglider/web/static/route_point_acquisition.js';
import {clearPointUndo,undoPointEdit,redoPointEdit,pointUndoLabel} from '../../src/sugarglider/web/static/route_edit_history.js';
import {initializeMap,renderPois,placeMapDiagnostics} from '../../src/sugarglider/web/static/map.js';
import {distribution} from './pr42_region_components_harness.js';
const assert=(v,m)=>{if(!v)throw Error(m)},eq=(a,b,m)=>assert(JSON.stringify(a)===JSON.stringify(b),m);
const until=async f=>{for(let i=0;i<240;i++){if(f())return;await new Promise(r=>setTimeout(r,25))}throw Error('Timeout')};
const categories=['toilets','cafe','bakery','picnic_area'];
function recount(d){d.features.sort((a,b)=>a.id.localeCompare(b.id));d.metadata.feature_count=d.features.length;for(const[k,v]of [['category_counts','category'],['access_counts','access_status'],['potability_counts','potability']]){d.metadata[k]={};for(const f of d.features)d.metadata[k][f[v]]=(d.metadata[k][f[v]]??0)+1}}
export async function run(){
 const cases=[],fixture=await(await fetch('../fixtures/pr40_regional_data.json')).json(),legacy=createLocalRegionData(fixture.manifest,structuredClone(fixture));
 const query={bbox:{west:0,south:0,east:.02,north:.02},categories,groups:['practical','refreshment'],limit:200};
 const html=new DOMParser().parseFromString(await(await fetch('/static/index.html')).text(),'text/html');
 for(const [id,key,checked]of [['toilets','toilets',true],['picnic-areas','picnicAreas',true],['cafes','cafes',false],['bakeries','bakeries',false]]){eq(html.querySelector('#place-'+id).checked,checked,'HTML default '+id);eq(state.poiFilters[key],checked,'State default '+id);cases.push('independent_control_default_'+id)}
 for(const [id,key,checked]of [['ice-cream','iceCream',true],['scenic','scenic',true],['verified-water','verifiedWater',true],['unknown-water','unknownWater',false],['broad','broadAttractions',false],['restricted','restrictedAccess',false],['private','includePrivate',false],['non-potable','nonPotable',false]]){eq(html.querySelector('#place-'+id).checked,checked,'Legacy HTML '+id);eq(state.poiFilters[key],checked,'Legacy state '+id)}cases.push('all_legacy_defaults_unchanged');
 for(const version of ['1','2','3']){fixture.manifest.tools.poi_classifier=fixture.pois.metadata.classifier_version=fixture.pois.metadata.build_configuration.classifier_version=version;const old=createLocalRegionData(fixture.manifest,structuredClone(fixture));eq(old.searchPois(query).returned_count,0,'No fabricated new records');const warning=placeCompatibilityMessage(['ice_cream',...categories],version);assert(version==='3'?!warning:warning.includes('practical-place'),'Version capability warning');if(version==='1')assert(warning.includes('ice-cream'),'Single combined warning');cases.push('classifier_'+version+'_compatibility_truthful')}
 const features=categories.map((category,i)=>({...structuredClone(fixture.pois.features[0]),id:'node/'+(900+i),osm_id:900+i,category,group:['toilets','picnic_area'].includes(category)?'practical':'refreshment',potability:'not_applicable',scenic_confidence:'none',display_name:i===0?'Toilets <img src=x onerror=alert(1)>':'Named '+category.replaceAll('_',' '),coordinate:{lat:.004+i*.004,lon:.01},approach_candidates:[],tags:[['addr:street','Rue test'],['fee','yes'],['opening_hours','Mo-Su 10:00-18:00']]}));
 fixture.pois.features.push(...features);recount(fixture.pois);const data=createLocalRegionData(fixture.manifest,structuredClone(fixture));
 for(const f of features){eq(data.searchPois({...query,categories:[f.category]}).features.map(x=>x.id),[f.id],'Exact category');assert(data.searchPlaceNames(f.display_name.replace(/<.*>/,'').trim()).results.some(r=>r.poiId===f.id||r.name===f.display_name),'Name search');eq(eligibleLocalPoi(f,fixture.manifest.bounds),'poi_category_display_only','Not automatic');assert(!isPriorityPlace(f),'Ordinary priority');const [min,label]=f.category==='picnic_area'?[13,15]:f.category==='toilets'?[14,16]:[15,16];eq([PLACE_PRESENTATIONS[f.category].minZoom,PLACE_PRESENTATIONS[f.category].labelZoom],[min,label],'Zoom policy');cases.push(f.category+'_filter_search_zoom_ordinary_no_auto_tour')}
 assert(data.searchPlaceNames('picnic area').results.some(r=>r.name==='Named picnic area'),'Friendly category search');cases.push('picnic_area_friendly_search');
 eq(data.queryPois({center:{lat:.01,lon:.01},radius_m:2000,limit:64}).features,legacy.queryPois({center:{lat:.01,lon:.01},radius_m:2000,limit:64}).features,'New practical/refreshment cannot crowd Auto Tour');cases.push('legacy_auto_tour_bounded_shortlist_unchanged');
 eq(data.searchPois({...query,groups:['practical']}).features.map(f=>f.category).sort(),['picnic_area','toilets'],'Practical group');eq(data.searchPois({...query,groups:['refreshment']}).features.map(f=>f.category).sort(),['bakery','cafe'],'Refreshment group');cases.push('exact_group_parity');
 const limited=data.searchPois({...query,limit:2});eq([limited.total_matching,limited.returned_count,limited.truncated],[4,2,true],'Truthful truncation');eq(limited,data.searchPois({...query,limit:2}),'Determinism');const all=data.searchPois({...query,groups:['scenic','hydration','refreshment','practical'],categories:['castle','drinking_water','fountain',...categories],limit:2});assert(all.features.every(f=>!categories.includes(f.category)),'Legacy bounded prefix preserved');cases.push('bounded_deterministic_truthful_truncation');
 for(const access of ['private','restricted']){const copy=structuredClone(fixture);copy.pois.features.filter(f=>categories.includes(f.category)).forEach(f=>f.access_status=access);recount(copy.pois);const d=createLocalRegionData(copy.manifest,copy);eq(d.searchPois({...query,access:['public','unknown']}).returned_count,0,'Hidden '+access);for(const f of copy.pois.features.filter(f=>categories.includes(f.category)))assert(resolvedPoiLocation(f)===null,'No pass '+access);cases.push(access+'_hidden_no_pass')}
 const origin=await navigator.storage.getDirectory(),folder='practical-'+crypto.randomUUID(),root=await origin.getDirectoryHandle(folder,{create:true}),versions=createRegionVersionStore({storage:{getDirectory:async()=>root,estimate:async()=>({quota:1e9,usage:0})},locks:navigator.locks}),client=createLocalRegionClient();
 try{const download=await distribution(fixture,'Practical fixture');await parseRegionalManifest(JSON.stringify(download.manifest));const components=(manifest,directory)=>createVersionedRegionComponents({manifest,directory,fetchResource:async url=>{const bytes=download.files.get(new URL(url).pathname.slice(1));return new Response(bytes,{headers:{'Content-Length':String(bytes.byteLength)}})},pageLocation:location});const ticket=await versions.stage(JSON.stringify(download.manifest));await versions.withStagedVersion(ticket,async({manifest,directory})=>{const c=await components(manifest,directory);await c.installMap(location.origin+'/manifest.json');await c.installIndexes(location.origin+'/manifest.json')});await versions.activate(ticket,{verifyComponent:async(kind,manifest,directory)=>{if(kind==='routing')return true;const c=await components(manifest,directory);if(kind==='map')return c.verifyMap();await c.openIndexes();return true}});const search=createLocalPlaceSearch({versions,regionClient:client,selectedRegionId:()=>download.manifest.region_id});eq((await search(query)).features,data.searchPois(query).features,'Committed OPFS real worker parity');cases.push('classifier3_manifest_opfs_worker_parity')}finally{client.close();await origin.removeEntry(folder,{recursive:true})}
 const initial=structuredClone(state);let ready=false,selected=null,placements=0;const endpoints=()=>state.planningMode==='auto_tour'?state.autoTour:state.waypointEndpoints;const assign=(kind,p)=>{saveActivePoints();assignRouteEndpoint(endpoints(),kind,p);if(state.planningMode==='auto_tour'&&kind==='start')state.points=[p,...state.autoTour.hardPoints].filter(Boolean)};
 const request=()=>endpoints().start?currentPlanRequest():null;const add=f=>addResolvedRouteLocation(resolvedPoiLocation(f),{assignEndpoint:assign});const choose=id=>{selected=id;renderPois(features,id,choose,{canPassThrough:f=>resolvedPoiLocation(f)!==null,onPassThrough:add,onDeselect:()=>choose(null)})};
 initializeMap({initial_center:[.01,.01],initial_zoom:16,offline_mode:true},{onReady:()=>{ready=true;choose(null)},onMapClick:()=>placements++,onError:m=>{throw Error(m)}});await until(()=>ready&&placeMapDiagnostics().markerIds.length);
 for(const f of features){Object.assign(state,structuredClone(initial));state.config={max_required_points:30};clearPointUndo();const before=request(),history=pointUndoLabel();choose(f.id);eq(request(),before,'Inspect unchanged');eq(pointUndoLabel(),history,'Inspect history unchanged');const popup=document.querySelector('.place-popup');assert(popup&&popup.querySelector('h3').textContent===f.display_name,'Plain text popup');assert(!popup.querySelector('img'),'No name markup');assert(popup.textContent.includes(PLACE_PRESENTATIONS[f.category].label),'Friendly label');assert(popup.textContent.includes('Rue test')&&popup.textContent.includes('Mapped fee: yes')&&popup.textContent.includes('OpenStreetMap'),'Mapped metadata credit');assert(!popup.querySelector('.popup-prefer'),'No Prefer');const pass=popup.querySelector('.place-pass-through');assert(pass&&!pass.hidden,'Pass present');pass.click();eq({name:endpoints().start.name,lat:endpoints().start.lat,lon:endpoints().start.lon},resolvedPoiLocation(f),'Name lat lon only');assert(!/osm_id|category|shop/.test(JSON.stringify(request())),'No POI metadata in canonical request');assert(state.request.status!=='running','No generation');assert(undoPointEdit(),'Undo');eq(request(),before,'Exact undo');assert(redoPointEdit(),'Redo');eq({name:endpoints().start.name,lat:endpoints().start.lat,lon:endpoints().start.lon},resolvedPoiLocation(f),'Exact redo');cases.push(f.category+'_safe_popup_inspect_pass_undo_redo_no_prefer_no_generate')}
 eq(placements,0,'No placement from inspect');choose(null);Object.assign(state,initial);return cases;
}
