import { state, saveActivePoints, assignRouteEndpoint, currentPlanRequest, invalidateCandidates } from '../../src/sugarglider/web/static/state.js';
import { appendMapIntent, changeMapTopology, reconcileAutomaticIntent } from '../../src/sugarglider/web/static/automatic_intent.js';
import { rememberPointEdit, commitPointEdit, undoPointEdit, redoPointEdit, clearPointUndo, pointRedoLabel, ROUTE_HISTORY_LIMIT } from '../../src/sugarglider/web/static/route_edit_history.js';
import { renderRouteDock } from '../../src/sugarglider/web/static/route_dock.js';
const assert = (ok, message) => { if (!ok) throw Error(message); };
const same = (a,b,message) => assert(JSON.stringify(a)===JSON.stringify(b),message);
const initial=structuredClone(state), A={lat:48.798432,lon:2.122484}, B={lat:48.790122,lon:2.118049}, C={lat:48.786583,lon:2.105706}, D={lat:48.783068,lon:2.120021};
const endpoints=()=>state.planningMode==='auto_tour'?state.autoTour:state.waypointEndpoints;
function reset(){Object.assign(state,structuredClone(initial));state.routingProfile='trail_run';clearPointUndo()}
function assign(kind,point){saveActivePoints();assignRouteEndpoint(endpoints(),kind,point);if(state.planningMode==='auto_tour'&&kind==='start')state.points=[point,...state.autoTour.hardPoints].filter(Boolean)}
const tap=p=>appendMapIntent(p,assign);
// Construct the former detailed-editor intent, using the unchanged canonical serializer.
function manual(kind,start,stops=[],end=null,order='fixed',topology='loop'){
 const saved=structuredClone(state);
 Object.assign(state,structuredClone(initial));state.routingProfile='trail_run';state.planningStrategy=kind;state.planningMode=kind;
 state.options=kind==='auto_tour'?{...state.options}:{...state.waypointOptions};state.options.waypointOrder=order;
 Object.assign(endpoints(),{start,end,routeTopology:topology});state.points=kind==='auto_tour'?[start,...stops].filter(Boolean):stops;
 const result=currentPlanRequest();Object.assign(state,saved);return result;
}
export async function runRouteDockHarness(){const cases=[];try{
 reset();tap(A);same(currentPlanRequest(),manual('auto_tour',{name:'Hard start',...A}),'1 Start loop canonical');cases.push('equivalence_start_only_loop');
 for(const p of[B,C,D])tap(p);let loop=currentPlanRequest();same(loop,manual('waypoint_route',loop.start,state.points),'2 fixed loop canonical');cases.push('equivalence_three_fixed_loop');
 rememberPointEdit('Order');state.options.waypointOrder='optimize';commitPointEdit();loop=currentPlanRequest();same(loop,manual('waypoint_route',loop.start,state.points,null,'optimize'),'3 optimized canonical');cases.push('equivalence_three_optimized_loop');
 const promoted=state.points.at(-1);changeMapTopology('point_to_point');assert(endpoints().end===promoted,'same point promoted');assert(state.points.length===2,'last stop removed only');let open=currentPlanRequest();same(open,manual('waypoint_route',open.start,state.points,open.end,'optimize','point_to_point'),'6 conversion canonical');cases.push('equivalence_loop_open_exact_promotion');
 const currentEnd=endpoints().end;changeMapTopology('loop');assert(state.points.at(-1)===currentEnd,'same End demoted');same(currentPlanRequest(),loop,'7 roundtrip canonical');cases.push('equivalence_open_loop_exact_demotion');
 reset();changeMapTopology('point_to_point');tap(A);tap(B);open=currentPlanRequest();same(open,manual('waypoint_route',open.start,[],open.end,'fixed','point_to_point'),'4 direct open canonical');cases.push('equivalence_start_end_open');
 const oldEnd=endpoints().end;tap(C);assert(state.points[0]===oldEnd&&endpoints().end!==oldEnd,'real End extends');tap(D);open=currentPlanRequest();same(open,manual('waypoint_route',open.start,state.points,open.end,'fixed','point_to_point'),'5 two stops open canonical');assert(new Set(state.points.map(p=>p.originalIndex).filter(Number.isInteger)).size===state.points.filter(p=>Number.isInteger(p.originalIndex)).length,'original indices unique');cases.push('equivalence_two_stops_open_extension');
 const final=structuredClone(open);let undone=0;while(undoPointEdit()){reconcileAutomaticIntent();undone++}assert(undone===5&&!endpoints().start&&state.points.length===0,'undo to zero including finish');let redone=0;while(redoPointEdit()){reconcileAutomaticIntent();redone++}assert(redone===undone,'multi redo');same(currentPlanRequest(),final,'redo exact');cases.push('multi_level_undo_to_empty_and_redo_exact');
 reset();tap(A);const auto=currentPlanRequest();tap(B);const wp=currentPlanRequest();assert(undoPointEdit(),'undo transition');same(currentPlanRequest(),auto,'8 restores auto');assert(redoPointEdit(),'redo transition');same(currentPlanRequest(),wp,'8 restores waypoint');cases.push('equivalence_history_auto_waypoint_transition');
 reset();state.planningMode='waypoint_route';state.planningStrategy='waypoint_route';state.options={...state.waypointOptions};state.waypointEndpoints.start={name:'Imported',...A};state.points=[{id:'soft-import',name:'Castle',...B,constraintStrength:'approach',accessSearchRadiusM:333,approachOverride:C}];const soft=structuredClone(state.points[0]);changeMapTopology('point_to_point');assert(!endpoints().end,'9 imported soft not promoted');same(state.points[0],soft,'soft identity unchanged');tap(D);open=currentPlanRequest();same(open,manual('waypoint_route',open.start,[soft],open.end,'fixed','point_to_point'),'9 soft canonical exact');cases.push('equivalence_imported_soft_stop_safety');
 reset();state.planningMode='waypoint_route';state.planningStrategy='waypoint_route';state.options={...state.waypointOptions};state.waypointEndpoints.start={...A};state.points=[{id:'imported-exact',name:'Imported exact stop',...B,constraintStrength:'exact'}];const importedExact=state.points[0];changeMapTopology('point_to_point');assert(!endpoints().end&&state.points[0]===importedExact,'imported exact stop is not silently promoted');cases.push('imported_exact_provenance_safety');
 reset();tap(A);tap(B);state.points[0].approachOverride=C;changeMapTopology('point_to_point');assert(!endpoints().end&&state.points.length===1,'override not promoted');cases.push('map_stop_with_override_not_promoted');
 reset();tap(A);state.planningMode='waypoint_route';state.waypointEndpoints={start:{...A},end:{...B,unrecognizedIntent:'retain'},routeTopology:'point_to_point'};state.points=[];const unsafe=structuredClone(state.waypointEndpoints);let rejected=false;try{changeMapTopology('loop')}catch{rejected=true}assert(rejected,'unknown End rejected');same(state.waypointEndpoints,unsafe,'rejection atomic');cases.push('unusual_end_conversion_rejected_atomically');
 reset();tap(A);tap(B);undoPointEdit();assert(pointRedoLabel(),'redo available');rememberPointEdit('No change');commitPointEdit();assert(pointRedoLabel(),'no-op retains redo');tap(C);assert(!redoPointEdit(),'new edit clears redo');cases.push('new_edit_clears_redo_noop_does_not');
 reset();tap(A);clearPointUndo();for(let i=0;i<ROUTE_HISTORY_LIMIT+8;i++){rememberPointEdit('Name');endpoints().start.name='Start '+i;commitPointEdit()}let depth=0;while(undoPointEdit())depth++;assert(depth===32,'strict history bound');cases.push('history_bounded_32');
 reset();tap(A);tap(B);rememberPointEdit('Constraint');state.points[0].constraintStrength='best_effort';state.points[0].maximumBestEffortDistanceM=700;commitPointEdit();const constrained=currentPlanRequest();undoPointEdit();assert(currentPlanRequest().waypoints[0].constraint_strength==='exact','strength undo');redoPointEdit();same(currentPlanRequest(),constrained,'constraint redo');cases.push('constraint_history_exact');
 state.request.status='running';assert(!undoPointEdit()&&!redoPointEdit(),'running guard');state.request.status='reversing';assert(!undoPointEdit(),'reversal guard');state.request.status='idle';state.savedRouteSnapshotDisplay=true;state.savedRouteSnapshot={};assert(!undoPointEdit(),'snapshot guard');state.savedRouteSnapshotDisplay=false;clearPointUndo();assert(!undoPointEdit()&&!redoPointEdit(),'import boundary');cases.push('history_running_reversal_snapshot_boundary_guards');
 reset();tap(A);tap(B);state.generationResult={candidates:[]};state.generationSourceRequest=currentPlanRequest();state.request.status='success';assert(undoPointEdit(),'history survives generation');invalidateCandidates();assert(!state.generationResult&&!state.generationSourceRequest&&state.resultsInvalidated,'stale results invalidated');cases.push('undo_after_generation_invalidates_results');
 const html=await(await fetch('../../src/sugarglider/web/static/index.html')).text();const doc=new DOMParser().parseFromString(html,'text/html');const root=doc.querySelector('#route-dock');const panel=document.createElement('div');panel.className='map-panel';panel.append(root);document.body.append(panel);
 reset();tap(A);tap(B);tap(C);let displayVisits=[];const draw=()=>renderRouteDock({root,disabled:false,visits:displayVisits,onSelectPoint:i=>{state.selectedPointIndex=i;state.selectedEndpointKind=null;draw()},onSelectEndpoint:k=>{state.selectedEndpointKind=k;state.selectedPointIndex=null;draw()},onMove:()=>{},onRemove:()=>{},onReorder:()=>{},onMoveEndpoint:()=>{},onClearEndpoint:()=>{}});draw();
 same([...root.querySelectorAll('[data-route-chip]')].map(b=>b.textContent),['S','1','2'],'strip canonical order');root.querySelector('[data-route-chip="0"]').focus();root.querySelector('[data-route-chip="0"]').click();assert(state.selectedPointIndex===0&&document.activeElement.dataset.routeChip==='0','chip selection/focus');assert(root.querySelector('[data-route-chip="0"]').getAttribute('aria-pressed')==='true','selected state');assert(root.querySelector('#route-quick-editor strong').textContent==='Stop 1','quick editor');same([...root.querySelectorAll('[data-dock-action]')].map(b=>b.textContent),['Move','Earlier','Later','Remove'],'visible quick actions');cases.push('strip_selection_quick_editor_keyboard_focus');
 displayVisits=[{original_index:1},{original_index:0}];draw();same([...root.querySelectorAll('[data-route-chip]')].map(b=>b.dataset.routeChip),['start','1','0'],'generated visit order matches map');root.querySelector('[data-route-chip="1"]').click();assert(state.selectedPointIndex===1&&root.querySelector('#route-quick-editor strong').textContent==='Stop 1','generated chip selects original object');cases.push('optimized_visit_strip_preserves_source_identity');displayVisits=[];draw();
 root.querySelector('[data-route-chip="start"]').click();assert(state.selectedEndpointKind==='start'&&state.selectedPointIndex===null,'exclusive endpoint selection');assert(root.querySelector('#route-quick-editor strong').textContent==='Start','Start editor');cases.push('endpoint_chip_same_selection_authority');
 assert(!root.querySelector('#undo-point-edit').hidden&&!root.querySelector('#redo-point-edit').hidden,'history always visible');assert(root.querySelector('#redo-point-edit').disabled,'redo disabled');assert(root.querySelector('#dock-finish').labels[0].textContent.includes('Finish'),'finish labeled');assert(root.querySelector('#dock-order').labels[0].textContent.includes('Order'),'order labeled');cases.push('labeled_visible_controls_disabled_history');panel.remove();
 }finally{Object.assign(state,initial);clearPointUndo()}return cases}
