// Real current Yvelines pack, actual map/touch controls, external routing process.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const O=process.env.UI2_EVIDENCE_DIR,B=process.env.UI2_BASE_URL||'http://127.0.0.1:8820',BEFORE=process.env.UI2_BASELINE_URL||'http://127.0.0.1:8821';
if(!O)throw Error('Set UI2_EVIDENCE_DIR outside Git.');
const sizes=[['phone390',390,844],['phone360',360,800],['phone412',412,915],['short',390,420],['text200',390,844],['desktop1280',1280,800],['desktop1440',1440,900]];
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});
try{for(const[name,width,height]of sizes.filter(v=>!process.env.VIEW_FILTER||v[0]===process.env.VIEW_FILTER||process.env.VIEW_FILTER==='other'&&v[0]!=='phone390'||process.env.VIEW_FILTER==='desktop'&&v[0].startsWith('desktop'))){
 const context=await browser.newContext({viewport:{width,height},isMobile:width<500,hasTouch:width<500,serviceWorkers:'block',reducedMotion:'reduce'}),page=await context.newPage();page.setDefaultTimeout(30000);
 const checks=[],entries=[],errors=[],requests={},equivalence=[],measurements=[];let routeCalls=0;const record=s=>{checks.push(s);console.log(name,s)};
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());page.on('request',r=>{if(/\/v2\/plans\/(generate|reverse)$/.test(r.url()))routeCalls++});
 await context.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
 await page.goto(B+'/setup');await page.evaluate(async()=>{await(await import('/static/map_pack_store.js')).createMapPackStore().installPack(location.origin+'/pack/map/manifest.json');const{openPwaStore,PWA_STORES}=await import('/static/pwa_store.js'),s=await openPwaStore();await s.put(PWA_STORES.trailProfile,'current',{schema_version:1,display_name:'Acceptance',avatar_key:'forest'});s.close()});
 await page.goto(B+'/');await page.evaluate(async()=>{window.S=await import('/static/state.js');window.M=await import('/static/map.js')});await page.waitForFunction(()=>window.S.state.config&&document.querySelectorAll('#profile option').length===6);
 if(name==='text200')await page.evaluate(()=>document.documentElement.style.fontSize='32px');
 async function view(v){const tab=page.locator(`[data-shell-view="${v}"]`);if(await tab.isVisible())await tab.click();await page.waitForTimeout(250)}
 async function expose(s){await page.locator(s).evaluate(el=>{for(let p=el.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true});await page.locator(s).scrollIntoViewIfNeeded()}
 async function req(){return page.evaluate(()=>window.S.currentPlanRequest())}
 async function tap(x,y){if(width<500)await page.touchscreen.tap(x,y);else await page.mouse.click(x,y);await page.waitForTimeout(200)}
 async function mapTap(lon,lat){await view('map');for(let zoom=0;zoom<6;zoom++){const ratio=await page.evaluate(()=>{const b=window.M.currentViewportBounds();return(b.east-b.west)/document.querySelector('#map').clientWidth});if(ratio<.000023)break;await page.locator('.maplibregl-ctrl-zoom-in').click();await page.waitForTimeout(250)}await page.evaluate(p=>window.M.focusCoordinate(p),[lon,lat]);await page.waitForTimeout(500);const q=await page.evaluate(p=>window.M.keepCoordinateVisible(p),[lon,lat]);const r=await page.locator('#map').boundingBox();await tap(r.x+q.x,r.y+q.y)}
 async function snap(label){await page.waitForTimeout(150);const file='after/'+name+'-'+label+'.png';await page.screenshot({path:path.join(O,file)});entries.push({label,file})}
 function overlaps(a,b){return a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.y+a.height>b.y}
 async function layout(label){await view('map');await page.waitForTimeout(150);const dock=await page.locator('#route-dock').boundingBox(),map=await page.locator('#map').boundingBox(),attrib=await page.locator('.maplibregl-ctrl-attrib').boundingBox(),nav=await page.locator('.maplibregl-ctrl-group').first().boundingBox();
  assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),'document overflow '+label);assert(dock.y>=map.y&&dock.y+dock.height<=attrib.y+1,'dock inside map above attribution '+label+' '+JSON.stringify({dock,map,attrib}));assert(!overlaps(dock,nav),'nav overlap');assert(dock.height<map.height/2,'map dominates '+label+' '+JSON.stringify({dock,map}));
  const location=page.locator('#planner-location-control');if(await location.isVisible())assert(!overlaps(dock,await location.boundingBox()),'location overlap');
  for(const selector of['#undo-point-edit','#redo-point-edit','.dock-choice','[data-route-chip]','[data-dock-action]'])for(const el of await page.locator('#route-dock '+selector).all()){if(!await el.isVisible())continue;const r=await el.boundingBox();assert(r.height>=43&&r.width>=43,'touch target '+selector)}
  assert(await page.locator('#dock-finish').isVisible());assert(await page.locator('#dock-order').isVisible());assert.equal(await page.locator('#route-dock').getByRole('combobox',{name:'Finish',exact:true}).count(),1);assert.equal(await page.locator('#route-dock').getByRole('combobox',{name:'Order',exact:true}).count(),1);measurements.push({label,height:dock.height});await snap(label);record(label+': layout, targets, attribution, navigation, overflow')}
 await layout('empty');assert(await page.locator('#undo-point-edit').isDisabled());assert(await page.locator('#redo-point-edit').isDisabled());
 await mapTap(2.122484,48.798432);const auto=await req();assert.equal(auto.kind,'auto_tour');await layout('start');
 if(name==='phone390'){await page.evaluate(p=>{window.M.focusCoordinate([p.lon,p.lat]);window.M.keepCoordinateVisible([p.lon,p.lat])},auto.start);await page.waitForTimeout(200);const marker=await page.locator('.required-marker[data-point-index="0"]').boundingBox();const x=marker.x+marker.width/2,y=marker.y+marker.height/2;await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+15,y+10,{steps:5});await page.mouse.up();await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>window.S.state.selectedEndpointKind),'start');assert.equal(await page.evaluate(()=>window.S.state.points.length),1);assert.equal(await page.locator('[data-route-chip="start"]').getAttribute('aria-pressed'),'true');assert.notDeepEqual((await req()).start,auto.start);await page.locator('#undo-point-edit').click();assert.deepEqual(await req(),auto);record('Start drag retains endpoint selection, creates no stop, Undo restores exact request')}

 for(const p of[[2.118049,48.790122],[2.105706,48.786583],[2.120021,48.783068]])await mapTap(...p);
 let loop=await req();assert.equal(loop.waypoints.length,3);assert.equal(loop.topology,'loop');assert.deepEqual(await page.locator('[data-route-chip]').allTextContents(),['S','1','2','3']);await layout('loop');

 // Completed gestures share app.js operations with the menu and Plan editor.
 const cdp=width<500?await context.newCDPSession(page):null;
 const finger=async(type,x,y)=>cdp?cdp.send('Input.dispatchTouchEvent',{type,touchPoints:type==='touchEnd'||type==='touchCancel'?[]:[{x,y,id:1}]}):type==='touchStart'?(await page.mouse.move(x,y),page.mouse.down()):type==='touchMove'?page.mouse.move(x,y):page.mouse.up();
 async function selectStop(i){const chip=page.locator(`[data-route-chip="${i}"]`);await chip.scrollIntoViewIfNeeded();if(await chip.getAttribute('aria-pressed')!=='true')await chip.click();return chip}
 async function beginDrag(i){const chip=await selectStop(i),r=await chip.boundingBox(),x=r.x+r.width/2,y=r.y+r.height/2;await finger('touchStart',x,y);await finger('touchMove',x+14,y);await page.waitForTimeout(70);assert(await page.locator('#route-drag-trash').isVisible(),'trash reveals after threshold');const location=page.locator('#planner-location-control');if(await location.isVisible())assert(!overlaps(await page.locator('#route-drag-trash').boundingBox(),await location.boundingBox()),'trash clear of recenter');return{x:x+14,y}}
 async function finishDrag(start,target,cancel=false){for(let i=1;i<=8;i++){await finger('touchMove',start.x+(target.x-start.x)*i/8,start.y+(target.y-start.y)*i/8);await page.waitForTimeout(25)}if(cancel&&cdp)await finger('touchCancel',target.x,target.y);else if(cancel){await page.keyboard.press('Escape');await finger('touchEnd',target.x,target.y)}else await finger('touchEnd',target.x,target.y);await page.waitForTimeout(120);assert(!await page.locator('#route-drag-trash').isVisible(),'trash clears after drop/cancel');assert.equal(await page.locator('.route-chip-ghost').count(),0,'ghost cleared')}
 const originalLoop=await req();await selectStop(0);let dragging=await beginDrag(0),targetBox=await page.locator('[data-route-chip="2"]').boundingBox();const dragTarget={x:targetBox.x+targetBox.width-3,y:targetBox.y+targetBox.height/2};await finishDrag(dragging,dragTarget);const reordered=await req();assert.deepEqual(reordered.waypoints.map(p=>p.coordinate),[originalLoop.waypoints[1].coordinate,originalLoop.waypoints[2].coordinate,originalLoop.waypoints[0].coordinate]);assert.equal(await page.evaluate(()=>window.S.state.selectedPointIndex),2);assert.equal(await page.locator('[data-route-chip="2"]').getAttribute('aria-pressed'),'true');await snap('drag-reordered');await page.locator('#undo-point-edit').click();assert.deepEqual(await req(),originalLoop,'one Undo reverses full drag');await page.locator('#redo-point-edit').click();assert.deepEqual(await req(),reordered);await page.locator('#undo-point-edit').click();record('native pointer drag reorder, one history edit, exact Undo/Redo, marker/chip sync');
 for(let i=0;i<2;i++){await page.locator('[data-dock-action="more"]').click();await page.locator('[data-dock-action="later"]').click()}
 assert.deepEqual(await req(),reordered,'drag vs existing Later exact canonical');for(let i=0;i<2;i++)await page.locator('#undo-point-edit').click();assert.deepEqual(await req(),originalLoop);record('drag reorder equals authoritative Move later final request');
 const historyLabel=await page.locator('#undo-point-edit').getAttribute('aria-label');dragging=await beginDrag(0);await finishDrag(dragging,dragTarget,true);assert.deepEqual(await req(),originalLoop);assert.equal(await page.locator('#undo-point-edit').getAttribute('aria-label'),historyLabel);assert(!await page.locator('#redo-point-edit').isDisabled());record('reorder cancellation preserves request, history and Redo');
 dragging=await beginDrag(0);let trash=await page.locator('#route-drag-trash').boundingBox();const trashCenter={x:trash.x+trash.width/2,y:trash.y+trash.height/2};await finger('touchMove',trashCenter.x,trashCenter.y);assert(await page.locator('#route-drag-trash').evaluate(e=>e.classList.contains('armed')));await snap('trash-armed');await finishDrag(trashCenter,trashCenter,true);assert.deepEqual(await req(),originalLoop);assert.equal(await page.locator('#undo-point-edit').getAttribute('aria-label'),historyLabel);record('armed trash cancellation preserves exact intent and history');
 dragging=await beginDrag(0);trash=await page.locator('#route-drag-trash').boundingBox();await finishDrag(dragging,{x:trash.x+trash.width/2,y:trash.y+trash.height/2});const removed=await req();assert.equal(removed.waypoints.length,2);await page.locator('#undo-point-edit').click();assert.deepEqual(await req(),originalLoop);await page.locator('#redo-point-edit').click();assert.deepEqual(await req(),removed);await page.locator('#undo-point-edit').click();await selectStop(0);await page.locator('[data-dock-action="more"]').click();await page.locator('[data-dock-action="remove"]').click();assert.deepEqual(await req(),removed,'trash and Remove request identical');await page.locator('#undo-point-edit').click();assert.deepEqual(await req(),originalLoop);record('trash drop = menu Remove, one history edit, exact Undo/Redo');
 await selectStop(1);let tapBox=await page.locator('[data-route-chip="1"]').boundingBox();await finger('touchStart',tapBox.x+22,tapBox.y+22);await finger('touchMove',tapBox.x+25,tapBox.y+24);assert(!await page.locator('#route-drag-trash').isVisible());await finger('touchEnd',tapBox.x+25,tapBox.y+24);assert.deepEqual(await req(),originalLoop);record('small pointer movement stays a tap; no reorder/removal');
 await selectStop(1);tapBox=await page.locator('[data-route-chip="1"]').boundingBox();await finger('touchStart',tapBox.x+22,tapBox.y+22);await page.waitForTimeout(550);assert(!await page.locator('#route-drag-trash').isVisible(),'long touch alone does not drag');if(cdp)await finger('touchCancel',tapBox.x+22,tapBox.y+22);else await finger('touchEnd',tapBox.x+22,tapBox.y+22);assert.deepEqual(await req(),originalLoop);record('long stationary touch does not initiate undocumented drag or edit');
 if(name==='phone390'){for(let i=0;i<3;i++){dragging=await beginDrag(0);trash=await page.locator('#route-drag-trash').boundingBox();await finishDrag(dragging,{x:trash.x+trash.width/2,y:trash.y+trash.height/2})}assert.equal((await req()).kind,'auto_tour');assert.deepEqual((await req()).start,originalLoop.start);assert.equal(await page.locator('[data-stop-index]').count(),0);for(let i=0;i<3;i++)await page.locator('#undo-point-edit').click();assert.deepEqual(await req(),originalLoop);for(let i=0;i<3;i++)await page.locator('#redo-point-edit').click();assert.equal((await req()).kind,'auto_tour');for(let i=0;i<3;i++)await page.locator('#undo-point-edit').click();assert.deepEqual(await req(),originalLoop);record('trash final stop restores Auto Tour, keeps Start, exact cross-mode Undo/Redo')}

 await page.locator('#dock-add').scrollIntoViewIfNeeded();await page.locator('#dock-add').click();assert.equal(await page.getByRole('dialog',{name:'Add point',exact:true}).count(),1);await snap('add-menu');await page.getByRole('button',{name:'Choose on map',exact:true}).click();assert(await page.evaluate(()=>window.S.state.addPointMode));await mapTap(2.1249,48.7934);const plusRequest=await req();assert.equal(plusRequest.waypoints.length,4);await page.locator('#undo-point-edit').click();assert.deepEqual(await req(),originalLoop,'plus add one edit');await mapTap(2.1249,48.7934);const directAdd=await req();fs.writeFileSync(path.join(O,'runtime',name+'-pixel-acquisition.json'),JSON.stringify({plusRequest,directAdd},null,2));const last=directAdd.waypoints.at(-1),plusLast=plusRequest.waypoints.at(-1);assert(Math.abs(last.coordinate.lat-plusLast.coordinate.lat)<.0001&&Math.abs(last.coordinate.lon-plusLast.coordinate.lon)<.0001,'same screen-acquired location within pixel precision');assert.deepEqual({...directAdd,waypoints:[...directAdd.waypoints.slice(0,-1),{...last,coordinate:plusLast.coordinate}]},plusRequest,'plus vs normal tap same canonical grammar');await page.locator('#undo-point-edit').click();record('Add route point menu / Choose on map uses normal grammar, one Undo item; exact resolved-input equivalence in harness');
 await selectStop(1);await page.locator('[data-dock-action="more"]').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelector('[data-dock-action="more"]')?.getAttribute('aria-expanded')==='true');assert.equal(await page.locator('[data-dock-action="more"]').getAttribute('aria-expanded'),'true');assert(await page.getByRole('dialog',{name:'Actions for Stop 2',exact:true}).isVisible());await snap('overflow-menu');await page.getByRole('button',{name:'Move earlier',exact:true}).focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>window.S.state.selectedPointIndex),0);assert.equal(await page.evaluate(()=>document.activeElement.dataset.routeChip),'0');await page.locator('#undo-point-edit').click();assert.deepEqual(await req(),originalLoop);await page.locator('[data-dock-action="more"]').click();await page.keyboard.press('Escape');assert(!await page.getByRole('dialog',{name:/Actions for/}).isVisible());assert.equal(await page.evaluate(()=>document.activeElement.dataset.dockAction),'more');record('keyboard overflow, reorder, Escape, semantic labels and rerender focus');
 // Tapping the selected chip closes the contextual row without changing intent.
 const selectedChip=page.locator('#route-point-strip [aria-pressed="true"]');await selectedChip.click();assert(await page.locator('#route-quick-editor').isHidden());assert.deepEqual(await req(),originalLoop);await layout('collapsed-idle');const baselineMeasurements=JSON.parse(fs.readFileSync(path.join(O,'before-measurements.json'),'utf8'));const oldIdle=baselineMeasurements.find(v=>v.name===name&&v.label==='idle');const newIdle=measurements.at(-1).height;assert(newIdle<oldIdle.height,'idle materially smaller');const oldSelected=baselineMeasurements.find(v=>v.name===name&&v.label==='selected');await selectStop(1);await layout('compact-selected');record(`dock height idle ${oldIdle.height} -> ${newIdle}; selected ${oldSelected.height} -> ${measurements.at(-1).height}`);
 // Reorder is explicitly disabled under Optimize; source intent stays unchanged.
 await page.locator('#dock-order').selectOption('optimize');const optimizedIntent=await req();await selectStop(1);await page.locator('[data-dock-action="more"]').click();assert(await page.locator('[data-dock-action="earlier"]').isDisabled());assert(await page.locator('[data-dock-action="later"]').isDisabled());assert(!await page.locator('[data-dock-action="remove"]').isDisabled());await page.keyboard.press('Escape');dragging=await beginDrag(1);targetBox=await page.locator('[data-route-chip="2"]').boundingBox();await finishDrag(dragging,{x:targetBox.x+targetBox.width-3,y:targetBox.y+22});assert.deepEqual(await req(),optimizedIntent);record('Optimize mode drag cannot alter editable source order; Remove remains available');
 await page.locator('#dock-order').selectOption('fixed');

 await page.locator('#dock-order').selectOption('optimize');assert.equal(await page.locator('#point-order-mode').inputValue(),'optimize');loop=await req();assert.equal(loop.waypoint_order,'optimize');record('dock / Plan visit order synchronization');
 async function generate(label){const expected=await req(),pending=page.waitForResponse(r=>r.url().endsWith('/v2/plans/generate'),{timeout:240000});await page.locator('#generate-top').click();const response=await pending;assert.equal(response.status(),200,await response.text());assert.deepEqual(response.request().postDataJSON(),expected);const result=await response.json();assert(result.candidates.length>0);await page.waitForFunction(()=>window.S.state.request.status==='success');requests[label]=expected;
  const baseline=await context.request.post(BEFORE+'/v2/plans/generate',{data:expected,timeout:240000});assert.equal(baseline.status(),200,await baseline.text());const previous=await baseline.json();
  const signature=r=>r.candidates.map(c=>({id:c.id,rank:c.rank,roles:c.roles,actual_waypoint_order:c.actual_waypoint_order,route:c.route.geometry,traversal:c.traversal}));assert.deepEqual(signature(result),signature(previous),'baseline candidates/order/geometry');
  await view('routes');await expose('#download-gpx');const pendingDownload=page.waitForEvent('download');await page.locator('#download-gpx').click();const downloaded=await pendingDownload;const file=path.join(O,'after',name+'-'+label+'.gpx');await downloaded.saveAs(file);
  const selected=await page.evaluate(()=>window.S.state.selectedSignature);const baselinePage=await context.newPage();await baselinePage.goto(BEFORE+'/setup');const prior=await baselinePage.evaluate(async c=>{const exp=(await import('/static/local_gpx_client.js')).createLocalGpxExporter();try{const r=await exp.exportCandidate(c);return await r.blob.text()}finally{exp.close?.()}},previous.candidates.find(c=>c.id===selected));await baselinePage.close();assert.equal(fs.readFileSync(file,'utf8'),prior,'GPX exact baseline');fs.writeFileSync(path.join(O,'before',name+'-'+label+'.gpx'),prior);
  fs.writeFileSync(path.join(O,'runtime',name+'-'+label+'.json'),JSON.stringify({request:expected,result,baseline:previous},null,2));equivalence.push({label,candidates:result.candidates.length,ids:true,order:true,geometry:true,gpx:true});await snap(label+'-routes');await view('map');record(label+': real generation, identical baseline candidate IDs/order/geometry/GPX')}
 if(name==='phone390'){await generate('loop-optimize');const generatedIntent=await req();await selectStop(1);dragging=await beginDrag(1);targetBox=await page.locator('[data-route-chip="0"]').boundingBox();await finishDrag(dragging,{x:targetBox.x+3,y:targetBox.y+22});assert.deepEqual(await req(),generatedIntent);record('generated optimized projection remains display-only during attempted drag');const markerPoint=await page.evaluate(()=>window.S.state.points[1]);await page.evaluate(p=>window.M.focusCoordinate([p.lon,p.lat]),markerPoint);await page.waitForTimeout(400);const marker=page.locator('.required-marker[data-point-index="1"]');await marker.focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>window.S.state.selectedPointIndex),1);assert.equal(await page.evaluate(()=>document.activeElement.dataset.pointIndex),'1');assert.equal(await page.locator('[data-route-chip="1"]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('.planner').getAttribute('data-view'),'map');record('marker keyboard activation selects same chip and retains focus on Map')}
 const previousLast=loop.waypoints.at(-1).coordinate;await page.locator('#dock-finish').selectOption('point_to_point');let open=await req();assert.equal(open.waypoints.length,2);assert.deepEqual(open.end,previousLast);await layout('open-promotion');
 const oldEnd=open.end;await mapTap(2.12710,48.7896);open=await req();assert.equal(open.waypoints.length,3);assert.deepEqual(open.waypoints.at(-1).coordinate,oldEnd);assert.notDeepEqual(open.end,oldEnd);await layout('open-extension');record('loop promotes last exact stop; map tap advances real End');
 if(name==='phone390')await generate('open-extended');
 const final=await req();let undone=0;while(!await page.locator('#undo-point-edit').isDisabled()){await page.locator('#undo-point-edit').click();undone++;assert(undone<40)}assert.equal(await page.evaluate(()=>window.S.state.autoTour.start),null);assert.equal(await page.locator('[data-route-chip]').count(),0);assert(!await page.evaluate(()=>window.S.state.generationResult));await layout('undo-empty');let redone=0;while(!await page.locator('#redo-point-edit').isDisabled()){await page.locator('#redo-point-edit').click();redone++;assert(redone<40)}assert.equal(redone,undone);assert.deepEqual(await req(),final);await layout('redo-exact');record('Undo to zero / Redo exact across modes, stale generated result cleared');
 const beforeUi=routeCalls;await page.locator('#dock-order').selectOption('fixed');await page.locator('[data-route-chip="1"]').click();assert.equal(await page.evaluate(()=>window.S.state.selectedPointIndex),1);assert.equal(await page.locator('#route-quick-editor strong').innerText(),'Stop 2');assert(await page.locator('.poi-row.selected').count()===1);
 await page.locator('[data-dock-action="move"]').click();await page.locator('[data-dock-action="move-map"]').click();await mapTap(2.1047,48.7871);assert.equal((await req()).waypoints.length,3);const afterMove=await req();assert(!await page.locator('#undo-point-edit').isDisabled());await page.locator('#undo-point-edit').click();const beforeMove=await req();assert.deepEqual(afterMove.waypoints.map((p,i)=>i===1?{...p,coordinate:beforeMove.waypoints[i].coordinate}:p),beforeMove.waypoints);await page.locator('#redo-point-edit').click();assert.deepEqual(await req(),afterMove);record('resolved map Move alters only selected coordinates and is one exact history edit');await page.locator('[data-dock-action="more"]').click();await page.locator('[data-dock-action="earlier"]').click();assert.equal(await page.evaluate(()=>window.S.state.selectedPointIndex),0);assert.equal(await page.locator('#route-quick-editor strong').innerText(),'Stop 1');await page.locator('[data-dock-action="more"]').click();await page.locator('[data-dock-action="later"]').click();assert.equal(await page.evaluate(()=>window.S.state.selectedPointIndex),1);await page.locator('[data-dock-action="more"]').click();await page.locator('[data-dock-action="remove"]').click();assert.equal((await req()).waypoints.length,2);assert(await page.locator('#redo-point-edit').isDisabled());await layout('quick-editor');record('chip Move / Earlier / Later / Remove synchronize with Plan and selection');
 for(const[k,p]of[['start',[2.1235,48.799]],['end',[2.1278,48.7903]]]){await page.locator(`[data-route-chip="${k}"]`).click();const count=(await req()).waypoints.length;await page.locator('[data-dock-action="move"]').click();await page.locator('[data-dock-action="move-map"]').click();await mapTap(...p);assert.equal((await req()).waypoints.length,count);assert.equal(await page.evaluate(()=>window.S.state.selectedEndpointKind),k)}record('Move Start / End create no duplicate stops');
 await page.locator('[data-route-chip="0"]').focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.dataset.routeChip),'0');await page.locator('[data-dock-action="more"]').click();await page.locator('[data-dock-action="later"]').focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.dataset.routeChip),'1');record('keyboard activation / focus retained through selection and reorder');
 for(const p of[[2.1199,48.786],[2.1263,48.784],[2.1269,48.786],[2.1253,48.788],[2.1212,48.7888]])await mapTap(...p);assert(await page.locator('[data-route-chip]').count()>=7);assert(await page.locator('#route-point-strip').evaluate(e=>e.scrollWidth>e.clientWidth),'long strip scrolls');await layout('long-strip');record('long point strip scrolls and keeps selected End visible');
 const manyIntent=await req(),stripBounds=await page.locator('#route-point-strip').boundingBox();
 await page.locator('#route-point-strip').evaluate(el=>el.scrollLeft=0);await finger('touchStart',stripBounds.x+200,stripBounds.y+22);for(let i=1;i<=8;i++){await finger('touchMove',stripBounds.x+200-i*20,stripBounds.y+22);await page.waitForTimeout(20)}await finger('touchEnd',stripBounds.x+40,stripBounds.y+22);await page.waitForTimeout(180);if(cdp)assert(await page.locator('#route-point-strip').evaluate(el=>el.scrollLeft>0),'native horizontal swipe');assert.deepEqual(await req(),manyIntent);assert(!await page.locator('#route-drag-trash').isVisible());record('native ribbon swipe scrolls unselected chips without route edit or trash');
 dragging=await beginDrag(0);const scrollBefore=await page.locator('#route-point-strip').evaluate(el=>el.scrollLeft);await finger('touchMove',stripBounds.x+stripBounds.width-5,stripBounds.y+22);await page.waitForTimeout(300);assert(await page.locator('#route-point-strip').evaluate(el=>el.scrollLeft)>scrollBefore,'drag edge autoscroll');assert.deepEqual(await req(),manyIntent,'preview never mutates');await finishDrag({x:stripBounds.x+stripBounds.width-5,y:stripBounds.y+22},{x:stripBounds.x+stripBounds.width-5,y:stripBounds.y+22},true);assert.deepEqual(await req(),manyIntent);record('edge autoscroll during drag, cancellation and pure preview');
 const boundsBefore=await page.evaluate(()=>window.M.currentViewportBounds()),mapRect=await page.locator('#map').boundingBox();const freeMapHeight=(await page.locator('#route-dock').boundingBox()).y-mapRect.y;const panX=mapRect.x+mapRect.width*.65,panY=mapRect.y+Math.min(160,freeMapHeight/2);await finger('touchStart',panX,panY);for(let i=1;i<=8;i++){await finger('touchMove',panX+i*8,panY+i*3);await page.waitForTimeout(20)}await finger('touchEnd',panX+64,panY+24);await page.waitForTimeout(200);assert.notDeepEqual(await page.evaluate(()=>window.M.currentViewportBounds()),boundsBefore,'map pan remains normal');assert.deepEqual(await req(),manyIntent);record('map pan gesture preserved without accidental route edit');
 const zoomBefore=await page.evaluate(()=>{const b=window.M.currentViewportBounds();return b.east-b.west});await page.locator('.maplibregl-ctrl-zoom-in').click();await page.waitForTimeout(400);const zoomAfter=await page.evaluate(()=>{const b=window.M.currentViewportBounds();return b.east-b.west});assert(zoomAfter<zoomBefore,'map zoom remains');record('native map zoom controls preserved; map.js and double-tap handlers unchanged');

 if(name==='phone390'){
  async function poi(category,topology){await page.locator('#dock-finish').selectOption(topology);await page.evaluate(cat=>window.M.focusCoordinate(cat==='ice_cream'?[2.1251258,48.8008765]:[2.1240874,48.8040423]),category);await page.waitForTimeout(850);await page.waitForFunction(cat=>window.S.state.poiFeatures.some(f=>cat==='ice_cream'?/lartecono/i.test(f.display_name):f.id==='node/2421490186'),category);const feature=await page.evaluate(cat=>window.S.state.poiFeatures.find(f=>cat==='ice_cream'?/lartecono/i.test(f.display_name):f.id==='node/2421490186'),category);
   await page.evaluate(f=>window.M.focusCoordinate([f.coordinate.lon,f.coordinate.lat]),feature);await page.waitForTimeout(850);const unchanged=await req(),placement=await page.evaluate(()=>({move:window.S.state.movingPointIndex,end:window.S.state.endpointSetMode}));let position=await page.evaluate(id=>window.M.placeMapDiagnostics().positions.find(f=>f.id===id).point,feature.id),r=await page.locator('#map').boundingBox();// Water icon collision leaves its visible label below the coordinate; tap that painted label.
   if(category==='ordinary')assert(await page.evaluate(id=>window.M.placeMapDiagnostics().labelIds.includes(id),feature.id),'ordinary label actually rendered');await tap(r.x+position[0],r.y+position[1]+(category==='ordinary'?22:0));await page.waitForFunction(({id,category})=>category==='ice_cream'?window.M.placeMapDiagnostics().popupId===id:Boolean(window.M.placeMapDiagnostics().popupId&&window.S.state.selectedPoiFeature?.category!=='ice_cream'),{id:feature.id,category});assert.deepEqual(await req(),unchanged);assert.deepEqual(await page.evaluate(()=>({move:window.S.state.movingPointIndex,end:window.S.state.endpointSetMode})),placement);assert(await page.locator('.maplibregl-popup-content').innerText());await snap('poi-'+category+'-'+topology);const inspectedId=await page.evaluate(()=>window.M.placeMapDiagnostics().popupId);
   if(category==='ice_cream'&&topology==='loop'){await page.locator('.maplibregl-popup-close-button').click();position=await page.evaluate(id=>window.M.placeMapDiagnostics().positions.find(f=>f.id===id).point,feature.id);const beforeZoom=await page.evaluate(()=>{const b=window.M.currentViewportBounds();return b.east-b.west});for(let i=0;i<2;i++){await finger('touchStart',r.x+position[0],r.y+position[1]);await finger('touchEnd',r.x+position[0],r.y+position[1]);await page.waitForTimeout(70)}await page.waitForTimeout(600);const afterZoom=await page.evaluate(()=>{const b=window.M.currentViewportBounds();return b.east-b.west});assert(afterZoom<beforeZoom,'native double tap zoom on inspect-only map feature');assert.deepEqual(await req(),unchanged);record('real native double-tap zoom on inspect-only POI preserves route intent');await page.locator('.maplibregl-ctrl-zoom-out').click();await page.waitForTimeout(300)}
   if(await page.locator('.maplibregl-popup-close-button').isVisible())await page.locator('.maplibregl-popup-close-button').click();record(category+' POI '+inspectedId+' with editor open in '+topology+' inspects only');return feature}
  const ice=await poi('ice_cream','loop');await poi('ordinary','loop');await poi('ice_cream','point_to_point');await poi('ordinary','point_to_point');
  // A nearby route point must not absorb the POI click, even during Move placement.
  await mapTap(ice.coordinate.lon+.00065,ice.coordinate.lat);await page.locator('[data-dock-action="move"]').click();await page.locator('[data-dock-action="move-map"]').click();await poi('ice_cream','point_to_point');assert.notEqual(await page.evaluate(()=>window.S.state.movingPointIndex??window.S.state.endpointSetMode),null);await page.locator('#cancel-point-placement').click();record('POI near route point and armed Move does not place or promote');
  await view('plan');await expose('#point-order-mode');await page.locator('#point-order-mode').selectOption('fixed');await view('map');assert.equal(await page.locator('#dock-order').inputValue(),'fixed');record('Plan → dock order synchronization');
 }
 assert.equal(routeCalls,beforeUi,'selection and edits never route automatically');await layout('final');assert.deepEqual(errors,[]);fs.writeFileSync(path.join(O,'after-'+name+'.json'),JSON.stringify({name,checks,entries,equivalence,requests,errors,routeCalls,measurements},null,2));await context.close();
}}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
