// Real-map acceptance; writes only to UI2_EVIDENCE_DIR. Never installs on a device.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('fs'),path=require('path'),assert=require('assert/strict');const O=process.env.UI2_EVIDENCE_DIR;
if (!O || !process.env.UI2_PLAN_PATH) throw Error('Set UI2_EVIDENCE_DIR outside Git and UI2_PLAN_PATH to a real Yvelines Start/End/three-stop request.');
fs.mkdirSync(path.join(O,'after'),{recursive:true});
const B=process.env.UI2_BASE_URL || 'http://127.0.0.1:8805',plan=JSON.parse(fs.readFileSync(process.env.UI2_PLAN_PATH));
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});const records=[];
for(const [name,width,height] of [['phone390',390,844],['desktop1440',1440,900]]){
const ctx=await browser.newContext({viewport:{width,height},isMobile:width<500,hasTouch:width<500,serviceWorkers:'block',reducedMotion:'reduce'}),page=await ctx.newPage(),checks=[],entries=[],errors=[];checks.push = (...items) => { console.log(name, ...items); return Array.prototype.push.apply(checks,items); }; page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));await ctx.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
await page.goto(B+'/setup');await page.evaluate(async()=>{await(await import('/static/map_pack_store.js')).createMapPackStore().installPack(location.origin+'/pack/map/manifest.json');const {openPwaStore,PWA_STORES}=await import('/static/pwa_store.js'),s=await openPwaStore();await s.put(PWA_STORES.trailProfile,'current',{schema_version:1,display_name:'UI review',avatar_key:'forest'});s.close()});await page.goto(B+'/');await page.evaluate(async()=>{window.S=await import('/static/state.js');window.M=await import('/static/map.js')});await page.waitForFunction(()=>window.S.state.config&&document.querySelectorAll('#profile option').length===6);
async function view(v){const b=page.locator(`[data-shell-view="${v}"]`);if(await b.isVisible())await b.click()}
async function expose(s){await page.locator(s).evaluate(el=>{for(let p=el.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true});await page.locator(s).scrollIntoViewIfNeeded()}
async function action(s){await view('plan');await expose(s);await page.locator(s).click()}
async function snap(label){await page.waitForTimeout(200);const file=`after/${name}-${label}.png`;await page.screenshot({path:path.join(O,file)});entries.push({label,file})}
async function request(){return page.evaluate(()=>window.S.currentPlanRequest())}
async function load(p=plan){await view('plan');await page.locator('#request-file').setInputFiles({name:'plan.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(p))});await page.waitForTimeout(250)}
async function tap(x,y){if(width<500)await page.touchscreen.tap(x,y);else await page.mouse.click(x,y);await page.waitForTimeout(200)}
async function background(f=.55){await view('map');await page.waitForTimeout(200);const r=await page.locator('#map').boundingBox();await tap(r.x+r.width*f,r.y+r.height*.65)}
await view('plan');await expose('input[name="planning-mode"][value="waypoint_route"]');await page.locator('input[name="planning-mode"][value="waypoint_route"]').check();const empty=await page.evaluate(()=>({endpoints:window.S.state.waypointEndpoints,points:window.S.state.points}));await background();assert(await page.evaluate(()=>!!window.S.state.waypointEndpoints.start));checks.push('ordinary tap with missing Start sets Start');
await action('#set-hard-start');assert(await page.locator('#map-edit-notice').isVisible());await background(.62);assert(await page.evaluate(()=>!!window.S.state.waypointEndpoints.start&&!window.S.state.endpointSetMode));assert(await page.locator('#generate').isDisabled());checks.push('explicit Start placement one-shot and loop still needs stop');
for(let i=0;i<3;i++){await action('#add-point-mode');await background(.45+i*.13);assert.equal(await page.evaluate(()=>window.S.state.points.length),i+1)}
assert(await page.locator('#generate').isEnabled());assert(await page.locator('#generate-top').isEnabled());const three=await request();await background(.76);assert.equal((await request()).waypoints.length,4);await page.locator('#undo-point-edit').click();assert.deepEqual(await request(),three);checks.push('three explicit stops; next ordinary tap adds a stop; Undo restores exactly');await snap('explicit-three-stops');
await view('plan');await expose('[data-point-index="1"] .point-select');await page.locator('[data-point-index="1"] .point-select').click();assert.equal(await page.evaluate(()=>window.S.state.selectedPointIndex),1);assert(await page.locator('.required-marker[data-point-index="1"]').getAttribute('aria-pressed')==='true');assert.equal(await page.locator('.point-popup').count(),0);const beforeMove=await request();await action('[data-action="place"]');assert((await page.locator('#map-edit-notice').innerText()).includes('new position'));await background(.73);const moved=await request();assert.equal(moved.waypoints.length,3);assert.notDeepEqual(moved.waypoints[1].coordinate,beforeMove.waypoints[1].coordinate);moved.waypoints[1].coordinate=beforeMove.waypoints[1].coordinate;assert.deepEqual(moved,beforeMove);checks.push('list and marker select same stop; Move changes only selected coordinate');
await action('[data-action="place"]');const cancelBefore=await request();await page.locator('#cancel-point-placement').click();assert.deepEqual(await request(),cancelBefore);assert(!await page.locator('#map-edit-notice').isVisible());checks.push('cancel movement preserves the route');
await view('map');const marker=page.locator('.required-marker[data-point-index="0"]');await marker.click();assert.equal(await page.evaluate(()=>window.S.state.selectedPointIndex),0);assert(await page.locator('[data-point-index="0"].poi-row.selected').count()===1);checks.push('map marker selects same authoritative list point');
await view('plan');await expose('[data-point-index="0"] .point-select');await page.locator('[data-point-index="0"] .point-select').focus();await page.keyboard.press('ArrowDown');assert.equal(await page.evaluate(()=>window.S.state.selectedPointIndex),1);await page.locator('[data-action="up"]').click();assert.equal(await page.evaluate(()=>window.S.state.selectedPointIndex),0);assert.equal(await page.evaluate(()=>document.activeElement?.closest('.poi-row')?.dataset.pointIndex),'0');assert(await page.locator('[data-action="up"]').isDisabled());await page.locator('[data-action="remove"]').click();assert.equal(await page.evaluate(()=>window.S.state.points.length),2);assert.equal(await page.evaluate(()=>document.activeElement?.closest('.poi-row')?.dataset.pointIndex),'0');checks.push('keyboard selection, boundary reorder and removal retain usable focus');
await load();await view('map');await page.locator('.endpoint-marker.start').click();assert.equal(await page.evaluate(()=>window.S.state.selectedEndpointKind),'start');assert.equal(await page.evaluate(()=>window.S.state.selectedPointIndex),null);checks.push('endpoint and stop selections mutually exclusive');
if(width>500){await view('map');await page.evaluate(()=>window.M.focusCoordinate([2.105706,48.786583]));await page.waitForTimeout(400);const r=await page.locator('.required-marker[data-point-index="1"]').boundingBox();const before=await request();await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await page.mouse.move(r.x+r.width/2+30,r.y+r.height/2+25,{steps:8});await page.mouse.up();await page.waitForTimeout(300);const after=await request();assert.notDeepEqual(before.waypoints[1].coordinate,after.waypoints[1].coordinate);after.waypoints[1].coordinate=before.waypoints[1].coordinate;assert.deepEqual(before,after);checks.push('existing marker drag changes only selected coordinate')}
await load();
for(const type of ['ice','ordinary']){
 await view('map');if(type==='ice'){await page.evaluate(()=>window.M.focusCoordinate([2.1251258,48.8008765]));await page.locator('.maplibregl-ctrl-zoom-in').click({clickCount:2})}
 else {
  // Known real Yvelines viewpoint. The first catalog result may have only a
  // label after normal basemap collision handling, so it is not an icon target.
  await page.evaluate(()=>window.M.focusCoordinate([2.1081054,48.7948727]));
 }
 await page.waitForFunction(type=>window.M.placeMapDiagnostics().markerIds.includes(type==='ice'?'node/9739373333':'node/700102346'),type);

 const id=type==='ice'?'node/9739373333':'node/700102346';
 for(const placing of [false,true]){
  if(placing)await action('#add-point-mode');await view('map');await page.waitForTimeout(300);await page.evaluate(point=>window.M.focusCoordinate(point),type==='ice'?[2.1251258,48.8008765]:[2.1081054,48.7948727]);await page.waitForFunction(id=>window.M.placeMapDiagnostics().markerIds.includes(id),id);const before=await request();const p=await page.evaluate(id=>{const p=window.M.placeMapDiagnostics().positions.find(p=>p.id===id).point,r=document.querySelector('.maplibregl-canvas').getBoundingClientRect();return{x:r.x+p[0],y:r.y+p[1]}},id);await tap(p.x,p.y-(type==='ice'?12:0));await page.waitForSelector('.maplibregl-popup');assert.equal(await page.evaluate(()=>window.M.placeMapDiagnostics().selectedId),id);assert.deepEqual(await request(),before);if(type==='ice')assert((await page.locator('.place-detail-popup').innerText()).includes('Lartecono'));if(placing){assert(await page.evaluate(()=>window.S.state.addPointMode));await snap(type+'-during-placement');await page.locator('#cancel-point-placement').click()}checks.push(type+' POI '+(placing?'during placement':'during exploration')+' display-only with intact details');await view('map');if(await page.locator('.maplibregl-popup-close-button').count())await page.locator('.maplibregl-popup-close-button').first().click();
 }
}
const rich=structuredClone(plan);rich.waypoints[1].constraint_strength='approach';rich.waypoints[1].approach_override={lat:rich.waypoints[1].coordinate.lat,lon:rich.waypoints[1].coordinate.lon};await load(rich);await page.locator('[data-point-index="1"] .point-select').click();const beforeConstraint=await request();await expose('[data-field="name"]');await page.locator('[data-field="name"]').fill('Explicit renamed stop');await page.locator('[data-field="name"]').dispatchEvent('change');const afterConstraint=await request();afterConstraint.waypoints[1].name=beforeConstraint.waypoints[1].name;afterConstraint.waypoints[1].coordinate.name=beforeConstraint.waypoints[1].coordinate.name;assert.deepEqual(afterConstraint,beforeConstraint);checks.push('editing imported flexible stop preserves override and bounds');
await load();await page.locator('[data-point-index="2"] .point-select').click();await expose('[data-field="name"]');await page.locator('[data-field="name"]').fill('Garden stop');await page.locator('[data-field="name"]').dispatchEvent('change');const editedRequest=await request();let generationCalls=0;page.on('request',r=>{if(r.url().endsWith('/v2/plans/generate')){generationCalls++;assert.deepEqual(r.postDataJSON(),editedRequest)}});await action('#generate');await page.locator('#generation-state').waitFor({state:'hidden',timeout:240000});await page.waitForFunction(()=>window.S.state.request.status==='success');await view('routes');assert(await page.locator('.candidate-select').count()>0);if(await page.locator('.candidate-select').count()>1)await page.locator('.candidate-select').nth(1).click();await page.waitForFunction(()=>window.M.directionMapDiagnostics().candidateId===window.S.selectedCandidate()?.id);await snap('edited-real-route');await expose('#download-gpx');const downloadPromise=page.waitForEvent('download');await page.locator('#download-gpx').click();const download=await downloadPromise;await download.saveAs(path.join(O,'after',name+'-edited.gpx'));assert.equal(generationCalls,1);await view('plan');assert.deepEqual(await request(),editedRequest);checks.push('real generation after name editing: Routes selection/map/export and return preserve draft, one generation');
for(const [label,w,h,scale] of [['short',390,420,1],['enlarged',360,640,2]]){await page.setViewportSize({width:w,height:h});await page.evaluate(scale=>document.documentElement.style.fontSize=16*scale+'px',scale);await view('plan');await expose('[data-point-index="1"] .point-select');await page.locator('[data-point-index="1"] .point-select').click();await expose('[data-action="remove"]');assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));assert((await page.locator('#map').boundingBox()).height>=110);assert((await page.locator('[data-action="remove"]').boundingBox()).height>=44);await snap(label+'-editor');await expose('#generate');assert(await page.locator('#generate').isEnabled());assert((await page.locator('#map').boundingBox()).height>=110);await snap(label+'-generate');checks.push(label+' text/viewport: map retained, 44px removal and Generate reachable without horizontal overflow')}
assert.deepEqual(errors,[]);records.push({name,checks,entries,errors});fs.writeFileSync(path.join(O,'interaction.json'),JSON.stringify(records,null,2));console.log(name,checks);await ctx.close();}
await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
