"""Generate offline display metadata from the sole public profile registry."""

import json
from pathlib import Path

from sugarglider.routing.profiles import ROUTING_PROFILES, public_profile


def render_profile_metadata() -> str:
    profiles = {
        profile.id: public_profile(profile).model_dump(mode="json")
        for profile in ROUTING_PROFILES
    }
    payload = json.dumps(profiles, ensure_ascii=False, indent=2, sort_keys=True)
    return (
        "// Generated by uv run python -m sugarglider.web.build_profile_metadata.\n"
        "// Display metadata only; installed native capabilities "
        "determine availability.\n"
        f"const profiles = {payload};\n"
        "function freeze(value) {\n"
        '  if (value && typeof value === "object") {\n'
        "    Object.values(value).forEach(freeze); Object.freeze(value);\n"
        "  }\n"
        "  return value;\n"
        "}\n"
        "export const PUBLIC_PROFILE_METADATA = freeze(profiles);\n"
    )


def main() -> None:
    destination = Path(__file__).parent / "static" / "public_profile_metadata.js"
    destination.write_text(render_profile_metadata(), encoding="utf-8")


if __name__ == "__main__":
    main()
