"""Generate the Android shell allowlist and environment-independent UI defaults."""

import json
import re
from pathlib import Path
from urllib.parse import unquote

from sugarglider.config import Settings
from sugarglider.web.config import build_ui_config

ANDROID_APP_ORIGIN = "https://appassets.androidplatform.net"
STATIC = Path(__file__).parent / "static"
EXTRA_ASSETS = (
    "android_ui_config.json",
    # Lazy HTML artwork is optional for the browser PWA cache, but Android's
    # bundled origin can serve only packaged files and has no network fallback.
    "brand/sugarglider-banner.png",
    "brand/sugarglider-flying-map.png",
    "index.html",
    "manifest.webmanifest",
    "vendor/maplibre-gl-6.4.1/LICENSE.txt",
    "vendor/pmtiles-4.5.0/LICENSE.txt",
    "vendor/protomaps-basemaps-5.7.2/LICENSE.md",
    "fonts/Open Sans Semibold/LICENSE.txt",
    "vendor/noble-hashes-2.4.0/LICENSE",
)


def render_android_ui_config() -> str:
    """Use canonical default settings without reading environment or .env files."""
    settings = Settings.model_construct().model_copy(
        update={
            "map_tile_url": (
                f"{ANDROID_APP_ORIGIN}/unavailable-tiles/{{z}}/{{x}}/{{y}}.png"
            ),
        }
    )
    config = build_ui_config(
        settings,
        nature_available=False,
        poi_available=False,
        saved_routes_available=False,
        outings_available=False,
        live_available=False,
    )
    return json.dumps(config.model_dump(mode="json"), indent=2, sort_keys=True) + "\n"


def render_android_shell_assets() -> str:
    """Package only the shared shell's declared runtime files and license notices."""
    source = (STATIC / "service-worker.js").read_text(encoding="utf-8")
    declaration = source.split("const CORE_ASSETS = Object.freeze([", 1)[1].split(
        "]);", 1
    )[0]
    assets = {
        unquote(path).removeprefix("/static/")
        for path in re.findall(r'"(/static/[^"\n]+)"', declaration)
    } | set(EXTRA_ASSETS)
    for path in assets:
        if (
            path.startswith("/")
            or "\\" in path
            or any(part in {"", ".", ".."} for part in path.split("/"))
            or not (STATIC / path).is_file()
            or (STATIC / path).is_symlink()
        ):
            raise ValueError(f"Invalid Android shell asset: {path}")
    return "# Generated by sugarglider.web.build_android_shell.\n" + "".join(
        f"{path}\n" for path in sorted(assets)
    )


def main() -> None:
    (STATIC / "android_ui_config.json").write_text(
        render_android_ui_config(), encoding="utf-8"
    )
    root = Path(__file__).resolve().parents[3]
    (root / "android" / "shell-assets.txt").write_text(
        render_android_shell_assets(), encoding="utf-8"
    )


if __name__ == "__main__":
    main()
