"""Generate canonical analysis templates for routes with no path details."""

import json
from pathlib import Path

from sugarglider.analysis.route import RouteAnalyzer
from sugarglider.routing.profiles import ROUTING_PROFILES


def render_local_analysis_templates() -> str:
    """Keep unknown native detail semantics owned by the Python domain analyzer."""
    analyzer = RouteAnalyzer()
    templates = {
        profile.activity_kind: analyzer.analyze(
            ((0.0, 0.0), (0.001, 0.0)),
            1.0,
            {},
            activity_kind=profile.activity_kind,
        ).model_dump(mode="json")
        for profile in ROUTING_PROFILES
    }
    # Only the unit-distance analysis is packaged. No synthetic geometry is
    # exported; the consumer computes geometry distance from the native line.
    for template in templates.values():
        del template["geometry_distance_m"]
        del template["distance_scale_factor"]
    payload = json.dumps(templates, ensure_ascii=False, indent=2, sort_keys=True)
    return (
        "// Generated by uv run python -m "
        "sugarglider.web.build_local_analysis_templates.\n"
        "// Unit-distance templates for absent path details, never route geometry.\n"
        f"const templates = {payload};\n"
        "function freeze(value) {\n"
        '  if (value && typeof value === "object") {\n'
        "    Object.values(value).forEach(freeze); Object.freeze(value);\n"
        "  }\n"
        "  return value;\n"
        "}\n"
        "export const UNKNOWN_DETAIL_ANALYSIS = freeze(templates);\n"
    )


def main() -> None:
    destination = Path(__file__).parent / "static" / "local_analysis_templates.js"
    destination.write_text(render_local_analysis_templates(), encoding="utf-8")


if __name__ == "__main__":
    main()
